### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Mpc46** [CGCookie/retopoflow#935] opened 2021-01-12 19:56 UTC
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

Pop up RANDOMLY appear .c

{*add any screenshots of the issue here*}
![RetopoFlow_screenshot](https://user-images.githubusercontent.com/43671013/104365625-d7cd6580-54dd-11eb-9cb4-c7842883018d.png)

**How to Reproduce:**

- working with the PolyPen and tweak tools

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.00.2
- Blender: 2.91.0 master 2020-11-25
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
- GPU: NVIDIA Corporation, GeForce RTX 3070/PCIe/SSE2, 4.5.0 NVIDIA 457.51, 4.50 NVIDIA
- Timestamp: 2021-01-12 13:54:34.277392
- Undo: insert, insert, insert, insert, select, select, select, select, select, select

Error Hash: 2ec5e386ae05c1abeb66dce8e1f1cb95

Trace:

- EXCEPTION (<class 'TypeError'>): cannot unpack non-iterable NoneType object
-     .../common\maths.py
- 000 1566:<genexpr>() min(x - 0.001 for (x, _) in self.v2Ds),
- 001 1566:__init__() min(x - 0.001 for (x, _) in self.v2Ds),
-     C:\Users\Diseño\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rf\rf_target.py
- 002 0113:get_vis_accel() self.accel_vis_accel = Accel2D(self.accel_vis_verts, self.accel_vis_edges, self.accel_vis_faces, self.get_point2D)
- 003 0126:accel_nearest2D_vert() if not vis_accel: vis_accel = self.get_vis_accel()
-     C:\Users\Diseño\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool_polypen\polypen.py
- 004 0192:set_next_state() self.nearest_vert,_ = self.rfcontext.accel_nearest2D_vert(max_dist=options['polypen merge dist'])
- 005 0282:main() self.set_next_state(force=True)
-     .../common\fsm.py
- 006 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment] 2021-01-12 20:10
Thanks for the report, @Mpc46 .  will take a look into it

**Comment by vxlcoder** [comment] 2021-01-30 22:18
this should now be fixed.  the list could possibly contain `None` values, which is the cause of this error.  now, we're filtering out these `None`s.

Will close this issue for now, but please let us know if you continue to have problems.

Thanks!

**Closed by vxlcoder** 2021-01-30 22:18 UTC
