### ISSUE TITLE
Weird overlay on macbook with Intel HD Graphics 5000

### ISSUE THREAD

**Issue by kostex** [CGCookie/retopoflow#576] opened 2018-08-02 05:49 UTC
Hi,

Following up on your advise, here's an issue I've got on OSX 10.12.6 and Intel HD 5000 gfx.
Using blender 2.79a
(I don't see this behaviour on same version os/blender/retopoflow on iMac5k with AMD GPU)

- Factory Defaults
- Enable Retopo addon 2.0.0

Made a small screen cap:
https://youtu.be/50kwjcAmVU8

Screenshot:
![screen shot 2018-08-02 at 07 49 39](https://user-images.githubusercontent.com/11047825/43564837-ab2c6b00-9628-11e8-83e4-07e7df75b10c.png)

Here's some system info:
[system-info.txt](https://github.com/CGCookie/retopoflow/files/2252252/system-info.txt)

**Comment by carter2422** [comment] 2018-08-02 15:17
Well at least it's pretty....

That's very strange @kostex, will have to have @vxlcoder look into this. It's almost certainly a BGL drawing issue.

**Comment by vxlcoder** [comment] 2018-08-02 15:39
Thanks for the report. Very interesting...

Have you tested in Blender 2.78b?

Also, can you try running from the terminal, and copy-paste here everything that gets printed there?

**Comment by kostex** [comment] 2018-08-02 17:54
Hi,
downloaded 2.78b
http://download.blender.org/release/Blender2.78/blender-2.78b-OSX_10.6-x86_64-fixed.zip

This version works as it should on same hardware!

2.79b started via terminal generated this:
```
/Applications/blender_279b.app/Contents/MacOS$ ./blender --factory-startup
found bundled python: /Applications/blender_279b.app/Contents/Resources/2.79/python
RetopoFlow Options path: /Users/kostex/Library/Application Support/Blender/2.79/scripts/addons/retopoflow-master/RetopoFlow_options.json
Caught exception while attempting to search for classes
  cls: RFTool: RFTool_Contours, RFTool_Stretch, RFTool_PolyStrips, RFTool_Tweak, RFTool_Strokes, RFTool_Patches, RFTool_Relax, RFTool_Stretch, RFTool_Loops, RFTool_PolyPen
  pyfile: tools.watch_profile
  No module named 'Levenshtein'
RetopoFlow updater verbose is enabled
RetopoFlow Updater: Read in json settings from file
RetopoFlow updater: Running background check for update
RFTools: RFTool_Contours RFTool_Stretch RFTool_PolyStrips RFTool_Tweak RFTool_Strokes RFTool_Patches RFTool_Relax RFTool_Stretch RFTool_Loops RFTool_PolyPen

```

**Comment by don-ferber** [comment] 2018-08-04 15:46
I have a similar looking effect as the above attached image, but with different colors. Looks sort of like weight painting mode. See attached. Also getting the Low FPS warning.

<img width="1049" alt="screen shot 2018-08-04 at 11 30 14 am" src="https://user-images.githubusercontent.com/42095485/43678139-a5d88760-97db-11e8-92fa-f6464dec2258.png">

<img width="260" alt="screen shot 2018-08-04 at 11 40 57 am" src="https://user-images.githubusercontent.com/42095485/43678144-afeebde6-97db-11e8-9fe7-5d54d9ba3d0a.png">

Details:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2017-09-11
- Platform: Darwin, 17.7.0, Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64, x86_64, i386
- GPU: Intel Inc., Intel Iris OpenGL Engine, 2.1 INTEL-10.36.19, 1.20
- Target: verts:64, edges:112, faces:48
- Sources: number:1, verts:482, edges:1440, faces:960
- FPS: current:1.913587, threshold:5, time:10

**Comment by grsbox** [comment] 2018-08-17 01:25
I have the same problem. I'm on a MacBook Pro (Retina, 15-inch, Mid 2015), Intel Iris Pro 1536 MB

**Comment by vxlcoder** [comment] 2018-08-17 01:48
Sorry, @kostex, I should have said 2.79b, not 2.78b.  Interesting that it seemed to work correctly with 2.78b, though.  Does it work correctly with 2.79b?

@don-ferber, it looks like you might also have an older version of Blender.  Can you try it using the latest 2.79b build?

@grsbox, what version of Blender are you using?

**Comment by kostex** [comment] 2018-08-17 07:16
@vxlcoder nope.. 2.79b is a no go too..

**Comment by grsbox** [comment] 2018-08-21 22:40
I'm using 2.79b

**Comment by Visheshl** [comment] 2018-09-25 12:07
Hey im having the same problem, retopoflow 2.0,mac mini blender 2.79... Wierd blue pink colours, any way to fix this problem?

**Comment by rlawhill** [comment] 2018-10-19 00:05
Same problem
Blender 2.79B
mac mini

**Comment by gavinbryars** [comment] 2019-02-05 17:16
I'm getting the same issue. I am using blender 2.79b on a Macbook pro. The version of Retopoflow I am using in this example is 2.0.3 but also happens with 2.0.2, 2.0.1 and 2.0.0. Anyone found a solution yet? Appreciate the help :)

![screen shot 2019-02-05 at 18 05 15](https://user-images.githubusercontent.com/13244360/52291215-224d1b80-2972-11e9-8f98-93a685ab2e80.png)

**Comment by carter2422** [comment] 2019-02-06 14:54
Thanks for the reports everyone. Unfortunately this seems to be relegated to certain GPU configurations and we've not yet found a fix for it.

**Comment by skyebasta** [comment] 2019-04-24 17:12
Have you already fix it?

**Comment by vxlcoder** [comment] 2019-04-24 17:40
sorry, @skyebasta, this is not fixed, yet.  I haven't been able to replicate the problem on a local machine for testing/debugging.  Our university has recently purchased a couple of macs, so I'll see if I can "convince" these machines to do the wrong thing.

**Comment by skyebasta** [comment] 2019-04-24 17:43
Actually, I uninstalled the 2.79 version of Blender and I installed the 2.78 one and it started to work properly! :)

**Comment by vxlcoder** [comment] 2019-04-24 17:45
really?!?  that's very strange!

I was nearly certain that the problem is with the GLSL shaders and the driver... and theoretically there should be nothing different between 2.79 and 2.78...  but maybe this is simply a Blender build problem.

**Comment by vxlcoder** [comment] 2019-04-24 17:46
i'll give it a go on the local macs when I get a chance.  you might try finding another build of 2.79b to see if that might work.  (or, if you know how to build blender from source, try that!)

**Comment by andreibosco** [comment] 2019-04-24 17:47
Yeah, I confirm that using 2.78 'fixes' the issue.

**Comment by vxlcoder** [comment] 2019-04-24 17:48
Thanks for the help!

This gives me a direction for debugging and testing!

**Comment by vxlcoder** [comment] 2021-09-02 16:07
Looking for issues similar to #1042, and this open issue came up.  This is an older bug (<= Blender 2.79) so I don't think it is an issue anymore.  Closing this issue for now, but please reopen with additional detail if this still needs attention.  thanks!

**Closed by vxlcoder** 2021-09-02 16:07 UTC
Labels: bug, help wanted, v2
