### ISSUE TITLE
[BUG] PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by dsguffey** [CGCookie/retopoflow#850] opened 2020-06-27 04:11 UTC
Blender 2.83. RetopoFlow 3-Beta-2

I was just try to join vertices.

![RetopoFlow_screenshot](https://user-images.githubusercontent.com/65681495/85914328-bf7c4e80-b80a-11ea-873c-fdad0eed7351.png)

**Comment by vxlcoder** [comment] 2020-06-29 13:39
Thanks for the report, @dsguffey.

I _think_ I've fixed this issue with commit 3719a1c, but I'm not sure what steps you took to cause this issue.

If you don't mind, can you either try testing out the latest commit or provide the steps you took to produce the error?

Thanks!

**Comment by dsguffey** [comment] 2020-06-29 22:56
I was trying to use PolyPen to drag one vertex onto another in order to
merge them, but it wasn't working. Possibly because one vertex was inside
the object and outside of the merge distance, but I could be getting it
confused with another issue I was having.

**Comment by vxlcoder** [comment] 2020-08-26 14:49
I'm going to close this issue for now, since I haven't been able to reproduce it.

Please reopen and post steps to reproduce / .blend file if you run into it again.

Thanks!

**Closed by vxlcoder** 2020-08-26 14:49 UTC
Labels: bug, help wanted, tool: polypen
