### ISSUE TITLE
Adjusting Target Alpha results in crash

### ISSUE THREAD

**Issue by Nocturael** [CGCookie/retopoflow#561] opened 2018-07-30 11:27 UTC
Tried to set the "Below" Target Alpha value, when it crashed

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0 beta 2
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1070/PCIe/SSE2, 4.5.0 NVIDIA 382.05, 4.50 NVIDIA


Error Hash: f91cdc7209a25f116ee55fe80868ee63


Trace:

- EXCEPTION (<class 'OSError'>): [Errno 22] Invalid argument: 'C:\\Users\\Nicolas Braun\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\retopoFlow\\RetopoFlow_options.json'
- .../options.py
- 000 0174:write() json.dump(Options.db, open(Options.fndb, 'wt'))
- 001 0172:__setitem__() self.write()
- 002 0207:_setter() options[key] = setwrap(v)
- .../common\ui.py
- 003 1283:mouse_move() self.fn_set_value(self.down_val + int((mouse.x - self.down_mouse.x)/10))
- 004 1925:modal_down() self.ui_down.mouse_move(self.mouse)
- 005 1846:modal() nstate = self.FSM[self.state]()
- 006 2056:modal() ret = self.active.modal(context, event)
- .../rfmode\rfcontext.py
- 007 0398:modal() ret = self.window_manager.modal(context, event)
```

**Comment by vxlcoder** [comment] 2018-07-30 13:45
Thanks for the report, @Nocturael.
Does RF crash like this if you change any other setting, such as "Auto Collapse Options" or "View Background Gradient"?

**Comment by vxlcoder** [comment] 2018-07-30 13:47
Also, how did you install RF?  Did you install from a .zip file using user prefs > add-ons > install, or did you copy the contents to the `addons` folder directly?

**Comment by Nocturael** [comment] 2018-07-30 14:17
It doesn't crash with other options, and I believe it has to do with the ability to set the value by mouse cursor position. I would assume I installed it via the options, but I am not 100% sure.

**Comment by vxlcoder** [comment] 2018-07-30 14:31
Very strange.  Everything works fine when you adjust target's Above Alpha?

**Comment by Nocturael** [comment] 2018-07-30 14:32
No, the same problem applies.

**Comment by vxlcoder** [comment] 2018-07-30 14:34
Try this: start RF, expand the Advanced section in Options window, click the Reset Options button.  Then, try adjusting the alpha values.

**Comment by Nocturael** [comment] 2018-07-30 14:51
Doesn't help.

**Comment by vxlcoder** [comment] 2018-07-30 15:12
Thanks for your patience and help with debugging this!
Will you tell me what happens when you adjust the "Initial Count" under Contours options?
What about when you change the Symmetry visualization to "None", "Edge", and "Face"?

**Comment by Nocturael** [comment] 2018-07-30 15:45
Changing the numbers that way works without problem.

**Comment by vxlcoder** [comment] 2018-07-30 15:50
Ok.  Let's try one other thing.  Can you try downloading and installing the latest version of the `release/2.0.0` branch?  If you're not familiar with git, you can use the link below to get a zip file.  Be sure to uninstall the current RF version first.

We have made some changes to the UI system, and I'm wondering if the changes will fix your issue.  (If so, then RF should continue to work moving forward.  If not, then there is still a bug that needs fixed.)

https://github.com/CGCookie/retopoflow/archive/release/2.0.0.zip

**Comment by vxlcoder** [comment] 2018-07-30 15:56
@Nocturael, I forgot one important item!  If you install via the link, you will need to rename the folder that it creates from `retopoflow-release-2.0.0` to `retopoflow`.  You will find it `C:\Users\Nicolas Braun\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\`.

**Comment by Nocturael** [comment] 2018-07-30 16:12
The issue still persists.

**Comment by vxlcoder** [comment] 2018-07-30 16:15
Thanks for doing that.  I'm investigating right now.

**Comment by vxlcoder** [comment] 2018-07-30 16:23
Since I cannot reproduce this bug here, I'll need you to collect some debugging info for me.

- Start Blender
- Open the System Console: Window > Toggle System Console.  Optionally, you can open Blender from the console, if you know how to do this.
- Leave the console open, but switch back to Blender
- Start RetopoFlow
- Under Advanced, set Debug Level to 2.  *NOTE*: you will need to click and edit, not drag!
- Change Symmetry visualization settings a few times
- Change the Symmetry Effect (should cause crash to show)
- Close RF
- Switch to the system console, copy the output, and paste it here

**Comment by Nocturael** [comment] 2018-07-30 16:46
Read prefs: C:\Users\Nicolas Braun\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
real_camera_addon updater verbose is enabled
Read in json settings from file
addon not found: 'retopoFlow'
RetopoFlow Options path: C:\Users\Nicolas Braun\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow\RetopoFlow_options.json
Caught exception while attempting to search for classes
  cls: RFTool
  pyfile: ext.gifextract
  No module named 'PIL'
Caught exception while attempting to search for classes
  cls: RFTool: RFTool_Loops, RFTool_Strokes, RFTool_PolyStrips, RFTool_Tweak, RFTool_Patches, RFTool_Stretch, RFTool_Contours, RFTool_Relax, RFTool_PolyPen
  pyfile: tools.watch_profile
  No module named 'Levenshtein'
RetopoFlow updater verbose is enabled
RetopoFlow Updater: Read in json settings from file
RetopoFlow updater: Running background check for update
RFTools: RFTool_Loops RFTool_Strokes RFTool_PolyStrips RFTool_Tweak RFTool_Patches RFTool_Stretch RFTool_Contours RFTool_Relax RFTool_PolyPen
DEBUG(2): Gather time: 0.00
DEBUG(2): Gather time: 0.00
DEBUG(2): Gather time: 0.00
DEBUG(2): Gather time: 0.00
DEBUG(2): Gather time: 0.00
DEBUG(2): Gather time: 0.00
DEBUG(2): Gather time: 0.00
DEBUG(2): Gather time: 0.00
EXCEPTION (<class 'OSError'>): [Errno 22] Invalid argument: 'C:\\Users\\Nicolas Braun\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\retopoflow\\RetopoFlow_options.json'
.../options.py
000 0210:write() json.dump(Options.db, open(Options.fndb, 'wt'))
001 0199:__setitem__() self.write()
002 0249:_setter() options[key] = setwrap(v)
.../common\ui.py
003 1746:mouse_move() self.fn_set_value(self.down_val + (mouse.x - self.down_mouse.x) / 10)
004 2248:modal_down() self.ui_down.mouse_move(self.mouse)
005 2180:modal() nstate = self.FSM[self.state]()
006 2377:modal() ret = self.active.modal(context, event)
.../rfmode\rfcontext.py
007 0437:modal() ret = self.window_manager.modal(context, event)
EXCEPTION (<class 'OSError'>): [Errno 22] Invalid argument: 'C:\\Users\\Nicolas Braun\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\retopoflow\\RetopoFlow_options.json'
.../options.py
000 0210:write() json.dump(Options.db, open(Options.fndb, 'wt'))
001 0199:__setitem__() self.write()
002 0249:_setter() options[key] = setwrap(v)
.../common\ui.py
003 1746:mouse_move() self.fn_set_value(self.down_val + (mouse.x - self.down_mouse.x) / 10)
004 2248:modal_down() self.ui_down.mouse_move(self.mouse)
005 2180:modal() nstate = self.FSM[self.state]()
006 2377:modal() ret = self.active.modal(context, event)
.../rfmode\rfcontext.py
007 0437:modal() ret = self.window_manager.modal(context, event)
EXCEPTION (<class 'OSError'>): [Errno 22] Invalid argument: 'C:\\Users\\Nicolas Braun\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\retopoflow\\RetopoFlow_options.json'
.../options.py
000 0210:write() json.dump(Options.db, open(Options.fndb, 'wt'))
001 0199:__setitem__() self.write()
002 0249:_setter() options[key] = setwrap(v)
.../common\ui.py
003 1746:mouse_move() self.fn_set_value(self.down_val + (mouse.x - self.down_mouse.x) / 10)
004 2248:modal_down() self.ui_down.mouse_move(self.mouse)
005 2180:modal() nstate = self.FSM[self.state]()
006 2377:modal() ret = self.active.modal(context, event)
.../rfmode\rfcontext.py
007 0437:modal() ret = self.window_manager.modal(context, event)
EXCEPTION (<class 'OSError'>): [Errno 22] Invalid argument: 'C:\\Users\\Nicolas Braun\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\retopoflow\\RetopoFlow_options.json'
.../options.py
000 0210:write() json.dump(Options.db, open(Options.fndb, 'wt'))
001 0199:__setitem__() self.write()
002 0249:_setter() options[key] = setwrap(v)
.../common\ui.py
003 1746:mouse_move() self.fn_set_value(self.down_val + (mouse.x - self.down_mouse.x) / 10)
004 2248:modal_down() self.ui_down.mouse_move(self.mouse)
005 2180:modal() nstate = self.FSM[self.state]()
006 2377:modal() ret = self.active.modal(context, event)
.../rfmode\rfcontext.py
007 0437:modal() ret = self.window_manager.modal(context, event)
DEBUG(2): Scaling view, sources, and target by 0.20

**Comment by vxlcoder** [comment] 2018-07-30 17:00
We think you _might_ have two copies of RF installed.  Can you try removing / uninstalling all copies of RF.  Then download the latest version of `release/2.0.0` again (I made some changes) and repeat the same steps above.
Thank you, again, for you help on this!

**Comment by Nocturael** [comment] 2018-07-30 17:13
Always glad to help, but I'm afraid it didn't work:
Read prefs: C:\Users\Nicolas Braun\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
real_camera_addon updater verbose is enabled
Read in json settings from file
RetopoFlow Options path: C:\Users\Nicolas Braun\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow\RetopoFlow_options.json
Caught exception while attempting to search for classes
  cls: RFTool
  pyfile: ext.gifextract
  No module named 'PIL'
Caught exception while attempting to search for classes
  cls: RFTool: RFTool_Strokes, RFTool_Patches, RFTool_Loops, RFTool_PolyPen, RFTool_Stretch, RFTool_Tweak, RFTool_PolyStrips, RFTool_Relax, RFTool_Contours
  pyfile: tools.watch_profile
  No module named 'Levenshtein'
RetopoFlow updater verbose is enabled
RetopoFlow Updater: Read in json settings from file
RetopoFlow updater: Running background check for update
RFTools: RFTool_Strokes RFTool_Patches RFTool_Loops RFTool_PolyPen RFTool_Stretch RFTool_Tweak RFTool_PolyStrips RFTool_Relax RFTool_Contours
EXCEPTION (<class 'OSError'>): [Errno 22] Invalid argument: 'C:\\Users\\Nicolas Braun\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\retopoflow\\RetopoFlow_options.json'
.../options.py
000 0212:write() json.dump(Options.db, open(Options.fndb, 'wt'))
001 0200:__setitem__() self.write()
002 0251:_setter() options[key] = setwrap(v)
.../common\ui.py
003 1746:mouse_move() self.fn_set_value(self.down_val + (mouse.x - self.down_mouse.x) / 10)
004 2248:modal_down() self.ui_down.mouse_move(self.mouse)
005 2180:modal() nstate = self.FSM[self.state]()
006 2377:modal() ret = self.active.modal(context, event)
.../rfmode\rfcontext.py
007 0437:modal() ret = self.window_manager.modal(context, event)
EXCEPTION (<class 'OSError'>): [Errno 22] Invalid argument: 'C:\\Users\\Nicolas Braun\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\retopoflow\\RetopoFlow_options.json'
.../options.py
000 0212:write() json.dump(Options.db, open(Options.fndb, 'wt'))
001 0200:__setitem__() self.write()
002 0251:_setter() options[key] = setwrap(v)
.../common\ui.py
003 1746:mouse_move() self.fn_set_value(self.down_val + (mouse.x - self.down_mouse.x) / 10)
004 2248:modal_down() self.ui_down.mouse_move(self.mouse)
005 2180:modal() nstate = self.FSM[self.state]()
006 2377:modal() ret = self.active.modal(context, event)
.../rfmode\rfcontext.py
007 0437:modal() ret = self.window_manager.modal(context, event)
EXCEPTION (<class 'OSError'>): [Errno 22] Invalid argument: 'C:\\Users\\Nicolas Braun\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\retopoflow\\RetopoFlow_options.json'
.../options.py
000 0212:write() json.dump(Options.db, open(Options.fndb, 'wt'))
001 0200:__setitem__() self.write()
002 0251:_setter() options[key] = setwrap(v)
.../common\ui.py
003 1746:mouse_move() self.fn_set_value(self.down_val + (mouse.x - self.down_mouse.x) / 10)
004 2248:modal_down() self.ui_down.mouse_move(self.mouse)
005 2180:modal() nstate = self.FSM[self.state]()
006 2377:modal() ret = self.active.modal(context, event)
.../rfmode\rfcontext.py
007 0437:modal() ret = self.window_manager.modal(context, event)
EXCEPTION (<class 'OSError'>): [Errno 22] Invalid argument: 'C:\\Users\\Nicolas Braun\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\retopoflow\\RetopoFlow_options.json'
.../options.py
000 0212:write() json.dump(Options.db, open(Options.fndb, 'wt'))
001 0200:__setitem__() self.write()
002 0251:_setter() options[key] = setwrap(v)
.../common\ui.py
003 1746:mouse_move() self.fn_set_value(self.down_val + (mouse.x - self.down_mouse.x) / 10)
004 2248:modal_down() self.ui_down.mouse_move(self.mouse)
005 2180:modal() nstate = self.FSM[self.state]()
006 2377:modal() ret = self.active.modal(context, event)
.../rfmode\rfcontext.py
007 0437:modal() ret = self.window_manager.modal(context, event)

**Comment by vxlcoder** [comment] 2018-07-30 17:18
Thanks!  It did get rid of a `addon not found` Blender error message.
Also, by chance, is your account running over a network or external hard drive?  I'm wondering this, because it seems the options are getting stored correctly a few times, but then it breaks.  Sometimes, this can be caused by a high-latency disk access, where many file writes are colliding when the OS is syncing the changes to a remote data store.  (note the Roaming in `Braun\AppData\Roaming\Blende`)

**Comment by Nocturael** [comment] 2018-07-30 18:38
The account runs from my SSD, but I'm syncing the appdata folder with my Dropbox, via a symbolic link. Shouldn't make a difference, just thought I might mention it.

**Comment by vxlcoder** [comment] 2018-07-30 18:44
It shouldn't, but I'm wondering if it is.  Is there any way that you could try installing Blender and RF to the local system, not in a roaming profile?  You can even download and extract a Windows Zip of Blender (non-installer) to a specific folder (say, `C:\Blender`), and then copy manually RF into the `addons` folder under there.  If it is a high-latency issue, then I'll have to write some code to delay the write (which isn't a big deal, but I'd like to add that complication only if it's necessary).  Thanks!

**Comment by Nocturael** [comment] 2018-07-30 19:03
Quitting Dropbox seems to solve the problem.

**Comment by vxlcoder** [comment] 2018-07-30 19:05
great!  glad that you found a workaround!
i'll see how hard it will be to delay the writes for roaming/remote folders.
Thanks again for your help!

**Comment by Nocturael** [comment] 2018-07-30 19:18
Glad to help.
One more question: I have an interesting behavior since installing the newer version.
While in RF mode, the RF mesh gets expanded, as if an offset was used in the shrinkwrap.
Is that a feature I haven't found the option for yet, or can I open a new issue? :D

**Comment by vxlcoder** [comment] 2018-07-30 19:44
commit 8566230 _should_ fix the Dropbox problem.  Try turning on Dropbox again and adjusting the values.  There is a 2second delay before writing.  Each time you change the value, the write delay starts over at 2seconds.  This should fix the problem (unless the remote/roaming folder is **really** slow, but then you probably shouldn't be running Blender or anything from it).

About the other question, please open a new issue, and post a screenshot.  We did add a slight offset for improved rendering, but maybe it's too strong for your model?

**Comment by vxlcoder** [comment] 2018-07-30 19:45
Thanks, again, for your help, @Nocturael!

**Comment by Nocturael** [comment] 2018-07-30 19:57
That seems to have fixed it. Thanks a lot. :)

**Comment by vxlcoder** [comment] 2018-07-30 20:41
glad to read!  closing this issue.

**Closed by vxlcoder** 2018-07-30 20:41 UTC
Labels: Ready for Testing, bug
