### ISSUE TITLE
When creating polygons in awkward angles( eg. creating arrowhead quads) retopoflow causes the ui to become unusable, unable to save and recover.

### ISSUE THREAD

**Issue by dodeqaa** [CGCookie/retopoflow#416] opened 2018-01-30 02:08 UTC
![screenshot 26](https://user-images.githubusercontent.com/35943639/35544438-4d6b81cc-05a5-11e8-945f-c18f79119cf1.png)
![screenshot 27](https://user-images.githubusercontent.com/35943639/35544439-4d9d8cda-05a5-11e8-9b6d-b8dc71d1a1c0.png)
![screenshot 28](https://user-images.githubusercontent.com/35943639/35544707-b7519c24-05a6-11e8-9ed3-295ddccc949d.png)

**Comment by dodeqaa** [comment] 2018-01-30 02:11
the ui navigation still works but ui elements disappear and menus, can be called via hotkeys but show up as blank boxes.

Blender 2.79 Windows 10 Pro Build 15063 64 bit
GtX1080TI x2
64GB DDR4
i7 7700k

**Comment by AidanMoure** [comment] 2018-02-06 03:40
Installed RetopoFlow today. Same problem.
Found that I'm getting that error message only when I'm using polypen, missing the sourse_object with ctrl+rmb and clicking on a view port. After that, few clicks later view port usually crashes and only blender reload helps

I thought, maybe other addons like hard ops and etc may somehow cause comapability issue, so I tried to disable everything exept RetopoFlow. Still got the error

**Comment by vxlcoder** [comment] 2018-02-21 14:52
Thanks for the report, @dodeqaa!

I'm not quite certain how to replicate your issue, but I did modify the part of the code that is breaking to be a bit more graceful.  If you can, please test commit e1db437, and let us know if you still have issues.  Otherwise, I'm hopeful that version 2.0 handles these issues better.

@AidanMoure, I have added a check to ensure that insertion code is run only when the cursor is over the source mesh.  Please check the latest commit, too.

Thanks!

**Comment by carter2422** [comment] 2018-03-27 20:27
@AidanMoure any chance you can test this again to see if it's working properly now? We've not been able to replicate the original report and so it's tricky to confirm.

**Comment by dodeqaa** [comment] 2018-03-28 01:28
Ill record a video this weekend if itll help?

**Comment by vxlcoder** [comment] 2018-03-28 14:11
That would be great, @dodeqaa. Thanks!

**Comment by dodeqaa** [comment] 2018-03-30 06:19
Heyo Here you guys go ,

Technically we would never create arrowheads like that, but it wouldn't do
to have it spazz out like that.

​
 2018-03-30-1413-47.flv
<https://drive.google.com/file/d/1aSnRcsqr1VOP4779dYgm4xbk5-PIDQid/view?usp=drive_web>
​

**Comment by dodeqaa** [comment] 2018-03-30 06:19
Goodluck for the code sprint!

**Comment by vxlcoder** [comment] 2018-03-30 11:03
Thanks @dodeqaa! Will take a look at this soon

**Comment by vxlcoder** [comment] 2018-03-30 16:59
@dodeqaa I just tried reproducing your bug, but I cannot get PolyPen to crash as it did with you.  When you created this video, were you using the latest version of RF 2.0?  I have found a few bugs over the past few days that could've been the cause of this, so this bug might be fixed now.  Thanks!

**Comment by dodeqaa** [comment] 2018-03-30 17:04
I see, ill update and give it a go, thanks!

**Comment by dodeqaa** [comment] 2018-03-31 05:58
Heyo, just update to 2.0 and its still doing it unfortunately.

**Comment by carter2422** [comment] 2018-03-31 14:46
Hey @dodeqaa, based on your video it seems you're using an older version of 2.0, as it doesn't have the pre-visualization while holding CTRL. 

Can you confirm that you have version 2.0.0-beta-1 by checking the version in File > User Preferences > Addons > RetopoFlow?

**Comment by carter2422** [comment] 2018-03-31 14:48
Could you try removing RetopoFlow entirely and then installing this version from zip? 
https://www.dropbox.com/s/zu41fpk6uogbtn6/RetopoFlow_v2.0.0-beta-1.zip?dl=0

**Comment by dodeqaa** [comment] 2018-04-01 06:36
Ok done, but its still happening unfortunately.

download video from :

https://drive.google.com/open?id=1aAhnIp0d5MvI6vE1H6_DXg8oglqSSPgN

**Comment by carter2422** [comment] 2018-07-19 20:15
@dodeqaa are you able to confirm that this issue is fixed for you in the beta 2 that was sent out? You can pull directly from `release/2.0.0` branch if you're familiar with Git.

**Comment by dodeqaa** [comment] 2018-07-20 05:05
Hi Jonathan!

I'm not familiar with pulling from GIT, how does that work?

I'll try to see if I can grab a download from Github in awhile.

Thanks for merging all the modes!

**Comment by dodeqaa** [comment] 2018-07-20 05:51
I'm not getting that error so far, so its good man.

I'm getting an error adjusting strength on the Tweak tool though, shift +
F  triggers the fly mode instead of adjusting the strength of the tweak.

**Comment by carter2422** [comment] 2018-07-25 17:56
@dodeqaa Fly Mode has been disabled in RetopoFlow to prevent the conflict. In the future we aim to add fully customizable keymaps in RetopoFlow, since invariably someone will request Fly Mode support :) 

Thanks for testing! Please do log an issue if you find anything else.

**Closed by carter2422** 2018-07-25 17:56 UTC
Labels: Ready for Testing, bug, tool: polypen
