### ISSUE TITLE
RetopoFlow broke while regestering

### ISSUE THREAD

**Issue by peregrine22** [CGCookie/retopoflow#743] opened 2019-09-20 19:44 UTC
[BUG]

This error occurred during installation.
![Screenshot_1](https://user-images.githubusercontent.com/12785343/65354397-1d369700-dbf8-11e9-807b-e42addaec404.jpg)

COULD NOT IMPORT RETOPOFLOW MODULES

Environment:
- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2017-09-11
- Platform: Windows, 10, 10.0.18362, AMD64, AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- GPU: ATI Technologies Inc., AMD Radeon HD 6700 Series, 4.5.13399 Compatibility Profile Context 15.201.1151.1008, 4.40
- Timestamp: 2019-09-20 22:35:06.346958

Exception: 
Error Hash: 2fb9dfdfc3a3d1a8a567dc5415d2ca9e
Trace:
    EXCEPTION (<class 'AssertionError'>): 
    .../common\shaders.py
    000 0068:shader_compile() assert False
    001 0132:__init__() logv = self.shader_compile(name, self.shaderVert)
    002 0113:load_from_file() return Shader(name, srcVertex, srcFragment, *args, **kwargs)
    003 0333:<module>() brushStrokeShader = Shader.load_from_file('brushStrokeShader', 'brushstroke.glsl', checkErrors=False, bindTo0='vPos')
    .../rfmode\rfwidget_brushstroke.py
    004 0026:<module>() from ..common.shaders import brushStrokeShader
    .../rfmode\rfwidget.py
    005 0036:<module>() from .rfwidget_brushstroke import RFWidget_BrushStroke
    .../rfmode\rftool.py
    006 0036:<module>() from .rfwidget import RFWidget_Default
    .../interface.py
    007 0040:<module>() from .rfmode.rftool import RFTool
    .../__init__.py
    008 0179:<module>() from .interface import (

**Comment by vxlcoder** [comment] 2019-09-20 20:23
Thanks for the report, @peregrine22.

Can you try starting Blender from console (or Window > Toggle System Console) and copy-paste everything that is printed to the console here?  There should be some more information there that can help debug this problem.

Thanks!

**Comment by peregrine22** [comment] 2019-09-21 07:14
It pretty much says the same thing.

At the beginning there's a bit of a new info: 
RetopoFlow version has changed.  Reseting options
ERROR WHILE COMPILING SHADER brushStrokeShader
    Vertex shader failed to compile with the following errors:
    ERROR: error(#271) Explicit version number 120 not supported by GL3 forward compatible context
    ERROR: error(#273) 1 compilation errors.  No code generated

**Comment by carter2422** [comment] 2019-11-21 15:06
Hey @peregrine22 apologies for the late reply on this. I'm closing this issue simply because RetopoFlow has been completely reworked for Blender 2.80 and so this issue should no longer be relevant. 

We will be releasing a beta for 2.8 anytime now; if the issue is still present then we can log a new issue.

**Closed by carter2422** 2019-11-21 15:06 UTC
