### ISSUE TITLE
Weird color overlay on Macbook Pro 

### ISSUE THREAD

**Issue by sundogdaze** [CGCookie/retopoflow#747] opened 2019-11-07 15:53 UTC
Weird color issue on Macbook Pro 2011 
Using Blender 2.79
Retopoflow version 2.0.3
HELPPPP!!!
![Screen Shot 2019-11-07 at 10 49 21 AM](https://user-images.githubusercontent.com/57198008/68404369-6f9e2980-014c-11ea-9a3c-d7653f13ca1f.png)

**Comment by vxlcoder** [comment] 2019-11-08 15:58
Thanks for the report, @sundogdaze!

I believe this is a similar issue to #576 and #673, which is sadly an ongoing issue.

However!  I believe that this issue will be resolved in the RetopoFlow updates for Blender 2.8x, which will be released very soon.  (See #746)  There are still a few issues to work out of the new RF for OSX, and I'm going to take a look at them this weekend.  If you're willing to test it out, keep an eye on the #746 issue and watch out for announcements for an alpha/beta version soon.

**Comment by sundogdaze** [comment] 2019-11-08 16:04
Jon Denning,

Thank you so much for reaching out!
Unfortunately I am un able to use Blender 2.8 on my version of
MacBook Pro.. so I won’t be able to use the fixed version of Retopoflow on
my computer.
If there is any chance of there being a bug fix for Blender 2.79 please let
me know!

Thanks,
Brendan

**Comment by carter2422** [comment] 2019-11-21 15:04
@sundogdaze that's unfortunate to hear. I'm afraid we've never been able to replicate or track down the cause of this display problem and so a bug fix is very unlikely.  

Closing as duplicate of #576

**Closed by carter2422** 2019-11-21 15:04 UTC
