### ISSUE TITLE
[QUESTION] Rotate view with Mouse Right Click isn't working, how can I fix it?

### ISSUE THREAD

**Issue by vickyinu** [CGCookie/retopoflow#1134] opened 2022-06-24 23:09 UTC
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [X] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [X] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.2.8

Blender Version/Hash: 3.2.0

Platform Version/Distribution: Github

&nbsp;

**Issue:**

My navigation keymapping on Blender is customized, I use the right mouse button to rotate the 3D view. That seems to break when using Retopoflow, as I can't seem to rotate with the right mouse button anymore

[add any screenshots of the issue here](https://youtu.be/7Plf6Img7vw)

&nbsp;

**How to Reproduce:**

* Change your rotate 3D view to Mouse Right Button
* Deactive the context menu
* Try to rotate the view with Right Mouse Button, notice that it works as expected
* Open retopoflow
* Try to rotate the view with Right Mouse Button, notice that the view doesn't rotate

{*[attach any files needed to replicate the issue](https://youtu.be/7Plf6Img7vw)*}

**Comment by jlampel** [comment] 2022-07-01 00:40
Thanks for reporting this! I was actually not able to reproduce this issue in Blender 3.2 and RetopoFlow 3.2.8. 

![image](https://user-images.githubusercontent.com/12982300/176799529-4dd0225b-4fa1-46af-a6f5-a6e05c1040ba.png)

![image](https://user-images.githubusercontent.com/12982300/176799554-1ffb99bb-33c2-4fb0-b553-2d4c463122ce.png)

I tried both with and without Emulate 3 Button Mouse enabled and even with right click select enabled (strangely), but it still seemed to work. Do you have any other customizations that could come into play here? Are you using a mouse or a tablet? And just out of personal curiosity, why do you prefer this setup? 

You can upload your preferences file if you'd like by going to user > AppData > Roaming > Blender Foundation > Blender > 3.2 > config > and userpref.blend.

**Comment by vickyinu** [comment] 2022-07-17 13:48
Hello @jlampel 

I have better reproduction steps.

I installed Blender and Retopoflow, without any changes on the preferences, and it was working as expected.

I then change the views again, like I mentioned, Right mouse to rotate, and tested it, still no problems.

I changed the Mouse Middle button to Move view, and that triggers the problem.

Actually what is causing the problem is the Mouse middle button.

I use the middle mouse to move the view, and the middle mouse is originally used to rotate the view.

Can you test it this with these steps and see if you can reproduce it?

These are my Blender prefs: https://drive.google.com/file/d/1eTUuepi40F3HpOEcATTV7oBGVftWtlMk/view?usp=sharing

I use this setup because I was looking for something that would work for all of the 3D software I use (Blender, Zbrush, Marvelous, etc...).
Zbrush doesn't have nearly as good customization as Blender, for example we have to install a plugin just to be able to use the Middle mouse on ZB.
That's why I decided to customize blender to something closer to zbrush view.

I'm using a tablet, a Cintiq 22.

**Comment by vxlcoder** [comment] 2022-08-03 13:06
Sorry for the delay in reply, @vickyinu.

I just downloaded your `userpref.blend` and tried it out, but it is working as expected on my machine.  MMB pans, RMB rotates, Wheel zooms...

Now, I just committed a _huge_ set of changes recently, and I'm using Blender 3.2.1, so it could be that either I or the Blender devs made a change that fixed this issue, but it could also just be my setup.

Could you try installing the latest Blender (if you haven't yet done so) and upgrading RetopoFlow to the `v3.3.0` branch?  You can enter `v3.3.0` into the `Advanced: Commit / Branch` field with the built-in updater system (see https://docs.retopoflow.com/addon_updater.html) to install the latest changes to test it out.

If for some reason the updater system does not work, let me know and I'll create a zip file to download and install.

Please let me know whether this works or not for you.  Thanks!

**Comment by jfranmatheu** [comment] 2024-12-16 13:42
Can't replicate this issue following the provided steps, under Blender 4.3 and RF 3.4.4, RMB does seems to work to rotate view in RF mode, even if using a tablet.

Closing issue due to prolonged inactivity. If the issue persists in later versions, please feel free to reopen it and provide further info. Thank you!

**Closed by jfranmatheu** 2024-12-16 13:42 UTC
Labels: can't replicate, need more info
