### ISSUE TITLE
PolyPen: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by Shakka57** [CGCookie/retopoflow#639] opened 2018-10-05 07:15 UTC
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2018-03-22
- Platform: Darwin, 17.7.0, Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64, x86_64, i386
- GPU: ATI Technologies Inc., AMD Radeon R9 M370X OpenGL Engine, 2.1 ATI-1.68.20, 1.20
- Timestamp: 2018-10-05 00:14:57.305114


Error Hash: 7b8b20170278afb7b60154fb5ba8160c


Trace:

- EXCEPTION (<class 'TypeError'>): glVertex2f() argument after * must be an iterable, not NoneType
- .../rfmode/rftool_polypen.py
- 000 0496:draw_lines() bgl.glVertex2f(*coords[0])
- 001 0576:draw_postpixel() self.draw_lines([bmv0.co, p0])
- .../common/profiler.py
- 002 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode/rfcontext_drawing.py
- 003 0137:draw_postpixel() self.tool.draw_postpixel()
```

**Comment by vxlcoder** [comment] 2018-11-29 01:51
I have tested all I could and was not able to reproduce this issue. I'm closing this issue, but feel free to reopen if it still happens. Thanks!

**Closed by vxlcoder** 2018-11-29 01:51 UTC
Labels: Ready for Testing, bug, tool: polypen
