### ISSUE TITLE
General bug: RetopoFlow causes Logitech software to hang 

### ISSUE THREAD

**Issue by TeoLions** [CGCookie/retopoflow#583] opened 2018-08-04 22:56 UTC
Hi! I just saw how awesome RetopoFlow is and decided to give it a try. I'm using Logitech's G600 mouse for modeling, since it have 20 buttons, which makes it ultimate tool for Blender. It works fine, but I've noticed that when RetopoFlow is active, it causing Logitech software to hang, making it impossible to use programmed shortcuts from the device. But if I switch the window or close RetopoFlow - it instantly unfreezing. 
I think that's something related to a way how this software getting what app is focus to change profile, because if you set Blender profile in it to "Lock profile while game is running" (which basically disallows it to change a profile since Blender is up), it works just fine.
Also I'm using Blender 2.79.6

**Comment by vxlcoder** [comment] 2018-08-05 11:56
Thanks for the report, @TeoLions.

This is a very strange issue.  We do not do anything different in RF than any other modal operator or Blender add-on would do.  In fact, we aren't even repositioning the cursor!  The closest thing I can think of is hiding the cursor in order to draw our own widgets, but any add-on can do this.

Below are a few questions to start the debugging process, but this might take a while to work through since I don't have a G600 on my end to test.  Thanks for your patience, and I'll do my best to figure out what's going on!

- Do you have this "freezing" or "hanging" only when you run RF, or does it occur even if RF isn't running, just enabled?
- Does Blender freeze, or just RF?  (you can test by using middle mouse button drag to scroll one of the other (darkened) panels, like the Properties or Outliner).
- What is your OS?
- Can you try reproducing this on another machine with your G600 mouse?  (especially if the other machine has a different OS!)
- Can you start Blender from a terminal/console, then start RF, attempt to do something, exit RF and Blender, then copy-paste everything from the terminal here.

Another test is this:

- Open Blender
- Switch to the Python Console
- Try typing this: `C.window.cursor_modal_set('NONE')` and press enter.  (This is effectively what RF does)
- Cursor should disappear... but does Blender/Logitech behave similarly to when running RF, the issue you're reporting on?
- You can restore the mouse cursor by typing: `C.window.cursor_modal_set('DEFAULT')` or moving the cursor off Blender.

**Comment by TeoLions** [comment] 2018-08-07 20:14
Due to further investigation turned out that it starting to hang not right away, but HOURS of switching windows. Restart of RF and Blender doesn’t seem to help, but restart of Logitech software does. Looks like the issue not with RF, but with this software, and I noticed it with RF just because I tend to switch windows more often while doing retopo. 
Sorry for false call!

**Comment by vxlcoder** [comment] 2018-08-07 20:25
Glad to hear that it's not a RF problem.  Closing this issue for now, but please reopen if you find anything new.  Thanks!

**Closed by vxlcoder** 2018-08-07 20:25 UTC
