### ISSUE TITLE
Normal offset not taking scale into account

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#667] opened 2018-11-29 01:22 UTC
Reproduce:

1. New
1. Delete all objects
1. Under Scene Properties, choose Kilometers preset.
1. Add cube
1. Press NUM-PERIOD (need to adjust clip start and end to something like 1cm--100m)
1. Deselect
1. Start Contours
1. Insert Cut

The rendered target is _far_ from the source.  A note: this is exactly what Blender does.

Another unfortunate side effect---one that I believe is caused by the Displace modifier---is that the vert normals get recomputed to something quite wonky!

Related to issue #643?

**Comment by jlampel** [comment] 2020-12-02 22:00
Adding this as a duplicate of https://github.com/CGCookie/retopoflow/issues/907

**Closed by jlampel** 2020-12-02 22:00 UTC
