### ISSUE TITLE
[BUG] Terrible lag when panning/rotating camera

### ISSUE THREAD

**Issue by HunterDoodles** [CGCookie/retopoflow#1212] opened 2023-04-18 01:05 UTC
Retopoflow Version: 3.3.0

Blender Version/Hash: 3.3.3 (Hash: 8d94aeb604fa)

Platform Version/Distribution: Windows (Blender Market Version)

**[BUG]**

Terrible lag when panning/rotating camera:

Rotating the view before Retopoflow is turned on is silky smooth, but Retopoflow has this terribly laggy viewport whenever I need to rotate or pan the camera around the model. It's making it pretty unusable! I saw posted that for some people a tablet is causing lag like this, and I do have a Huion tablet plugged in, but I'm not using it. It's on my other screen. I'm not sure if that's the cause of the issue.

Below is a video link of the issue in question.

https://drive.google.com/file/d/1rdGC0XWPIUjeYfYwHOfMsBpM9szwlWTr/view?usp=sharing

I've tried using older versions of Blender and Retopoflow but I still have this issue. Assistance would be much appreciated!

**Comment by vxlcoder** [comment] 2023-04-18 10:49
Thanks for the report and video, @HunterDoodles!

This is very strange behavior.  I have a few questions that might help narrow down the cause:

- Does the lag appear on the default scene and cube?
- Does the lag appear if you create a brand new target but still have the same source as in video?
- Does the lag appear regardless of which RetopoFlow tool is current?
- What are the specs of your machine?

**Comment by HunterDoodles** [comment] 2023-04-20 04:59
- The lag does not appear in the default scene and cube!

- The lag does not appear when I create a brand new target but still have the same source as in the video!

- The lag appears regardless of which Retopoflow tool is current.

- I'm running Windows 11, I have 64 GB's of RAM, a 4070 TI, and an 11th gen Intel i9 11900k CPU.

I'm very sad that the model doesn't lag when I switch targets. Hopefully, there's a way to not remove all that work. His head is a pain to retopologize.

**Comment by vxlcoder** [comment] 2023-04-20 11:03
Thank you for the details!  that gives me something to work with.

Would you mind sharing your .blend file with us at retopoflow@cgcookie.com?  I wonder if there is something particular about those meshes that we haven't seen before.

Thanks again!

**Comment by HunterDoodles** [comment] 2023-04-20 20:52
> Thank you for the details! that gives me something to work with.
> 
> Would you mind sharing your .blend file with us at [retopoflow@cgcookie.com](mailto:retopoflow@cgcookie.com)? I wonder if there is something particular about those meshes that we haven't seen before.
> 
> Thanks again!

I've gone ahead and sent an email!

**Comment by HunterDoodles** [comment] 2023-05-02 02:48
I look forward to an update!

**Comment by vxlcoder** [comment] 2023-05-06 16:37
@HunterDoodles, i _think_ i've found a good fix for this issue.  would you mind testing out the latest version of RF (temp zip at https://www.dropbox.com/s/bee8gmq16escltz/RetopoFlow_v3.3.1-alpha-GitHub.zip?dl=0) to see if performance is improved on your end?

again, thanks for your help on this!

**Comment by HunterDoodles** [comment] 2023-05-06 19:25
Like magic, the issue appears to be gone! In fact, the performance is smoother than I usually get when it's working normally! This is awesome! C:

**Comment by vxlcoder** [comment] 2023-05-06 19:37
so glad to hear!  closing this issue now, but let us know if you have any other problems. we would appreciate a rating on the blender market.

happy retopo'ing!

**Closed** 2023-05-06 19:37 UTC
Labels: Ready for Testing, performance bug
