### ISSUE TITLE
Switch to use OpenGL 3+

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#150] opened 2015-10-11 16:42 UTC
once bgl supports OpenGL 3+ API (it may already with 2.76 release), replace all immediate mode drawing code to use newer API.  this means rewriting code to use buffers, shaders, etc.  benefit: much faster rendering (!!!), cleaner render code paths, better integration with new viewport, and it's just a better way to live.

**Comment by carter2422** [comment] 2016-01-02 16:54
Duplicate of #173

**Closed by carter2422** 2016-01-02 16:54 UTC
