### ISSUE TITLE
[BUG] Crash to Desktop after launching RF

### ISSUE THREAD

**Issue by SkaveRat** [CGCookie/retopoflow#980] opened 2021-03-23 06:38 UTC
Retopoflow Version: 3.00.2 & 3.1.0

Blender Version/Hash: 2.92.0 02948a2cab44

Platform Version/Distribution:  Win10

**Issue:**

CTD after launching RF for the first time in a project.

Sculpted my character and started RF for the first time this project. It showed the loading dialogs and the welcome screen, but blender crashed a second after that. Stacktrace below.

It was reproducible. Crash every time when I started RF. Didn't matter what target was selected.

What I tried:
* Updating from 3.00.2 to 3.1.0 (both github releases)
* Changing render from eevee to cycles

**What fixed it for me:**  
I started hiding every mesh and activated each one by one. Even just showing the first one was enough for RF to launch. It was then possible to show every mesh again and RF seems to work flawlessly.

No idea if that has to do with the problem, but that seemed to fix it for me.

**How to Reproduce:**
No really sure.

```
# Python backtrace
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh.py", line 656 in raycast
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rf\rf_sources.py", line 109 in raycast_sources_Ray
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rf\rf_sources.py", line 119 in raycast_sources_Point2D
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rf\rf_sources.py", line 126 in raycast_sources_mouse
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rf\rf_states.py", line 81 in update
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rf\rf_drawing.py", line 60 in predraw
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\addon_common\common\drawing.py", line 1476 in _call
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\addon_common\common\drawing.py", line 1481 in _pre
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\addon_common\common\drawing.py", line 1484 in pre3d
  File "C:\Users\SkaveRat\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\addon_common\cookiecutter\cookiecutter_ui.py", line 101 in preview
```

**Comment by vxlcoder** [comment] 2021-06-02 20:29
Thanks for the report, @SkaveRat.  This is a strange bug, and unfortunately i'm not able to reproduce it.

are you still having this issue?

**Comment by SkaveRat** [comment] 2021-06-03 00:02
Not so far, but I didn't use RF a lot since reporting the issue

**Comment by jlampel** [comment] 2023-03-01 18:04
Closing this out since we're well past version 3.1 and haven't seen this come up since. Please let us know if you see it again!

**Closed by jlampel** 2023-03-01 18:04 UTC
Labels: can't replicate
