### ISSUE TITLE
Loops: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by andreighinea1** [CGCookie/retopoflow#571] opened 2018-07-31 18:20 UTC
This happened when I've tried to use the tool "Loops" with an object that has a thickness modifier applied to it

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1080 Ti/PCIe/SSE2, 4.6.0 NVIDIA 388.13, 4.60 NVIDIA
- Timestamp: 2018-07-31 21:16:39.240780


Error Hash: 7f66f106d8c76047fb3038f37023410c


Trace:

- EXCEPTION (<class 'ZeroDivisionError'>): float division by zero
- .../rfmode\rftool_loops.py
- 000 0352:modal_slide() percent = clamp(self.percent_start + a.dot(b) / a.dot(a), -1, 1)
- .../common\profiler.py
- 001 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rftool.py
- 002 0076:wrapper() ret = fn(*args, **kwargs)
- 003 0110:modal() nmode = self.FSM[self.mode]()
- 004 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 005 0556:modal_main() self.tool.modal()
- 006 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by andreighinea1** [comment] 2018-07-31 18:42
I also need to mention that I had the target selected, after I deselected it it worked

**Comment by carter2422** [comment] 2018-07-31 18:50
Thus far I've not been able to replicate the error. 

Can you walk me through the steps you took and perhaps share the .blend file @andreighinea1?

**Comment by vxlcoder** [comment] 2018-08-01 02:45
I'll take a look at this soon.  @andreighinea1, if you could post a screenshot, .blend file, or steps to reproduce this error, that would be super helpful.  Thanks!

**Comment by vxlcoder** [comment] 2018-08-01 15:10
@andreighinea1, I believe that your target mesh may have an edge with zero length.  In other words, you have either 2 vertices that are at the same location, or somehow an edge was created from one vertex to the same vertex.  If you can, try removing doubles in your target mesh using Blender's Edit Mode then retry using RF's Loops tool, and let us know if it worked.  I'll work up some better checks in RF for the next release.

Thanks!

**Comment by vxlcoder** [comment] 2018-08-01 15:40
commit 274b43e contains code to detect and prevent this issue.  also, added in buttons to remove doubles.

**Comment by andreighinea1** [comment] 2018-08-02 15:00
Hello, sorry for coming back this late.
I can confirm that I had some vertices in the same place, but that's not causing the issue. I've figured out how this can be reproduced:
Add 1 cylinder to an empty scene and 1 other mesh(with space between them). Select the other mesh and enter in retopo mode. If you now try to use the loop tool it'll try to use the cylinder as the retopologized mesh, and it'll give you this error:
https://imgur.com/a/YfVK2dF

**Comment by carter2422** [comment] 2018-08-02 15:14
Thus far I'm not able to replicate the error, possibly due to @vxlcoder's commit above. 

Following your steps I get expected (if undesirable) results by cutting loops into a mesh that's offset from the source surface: 
<img width="628" alt="screen shot 2018-08-02 at 10 14 00 am" src="https://user-images.githubusercontent.com/1648631/43593217-dc9c6fa0-963c-11e8-9118-ab28fa41e4dc.png">

**Comment by andreighinea1** [comment] 2018-08-02 18:48
Here's how I set-up the scene:
https://drive.google.com/open?id=1X2EsaO57hkC-x2wNc_VQ-KsRTTodd-rH

**Comment by vxlcoder** [comment] 2018-11-29 00:57
I, too, cannot reproduce this bug, so I believe it is fixed and will close the issue.  If we have missed in @andreighinea1, please reopen this issue.  Thanks!

**Closed by vxlcoder** 2018-11-29 00:57 UTC
Labels: Ready for Testing, tool: loops
