### ISSUE TITLE
Tweak Tool Brush Size Wont Change

### ISSUE THREAD

**Issue by CYTE2142** [CGCookie/retopoflow#363] opened 2017-10-05 07:48 UTC
Hey Everybody,
i have a problem with the tweak tool brush size. i press f and get the gizmo to change the brush size. i change the size and click. unfortunately the brush size stays unchanged. im using windows 10, blender 2.79.
any help or hint is very welcome.
Cheers Philipp

**Comment by carter2422** [comment] 2017-10-05 14:48
Hey Philipp, this is typically caused by the transforms of either the Source or Target object. Try selecting both objects in Object Mode and press CTRL+A > Apple Scale, Rotation. 

It should then work. 

This issue will be totally resolved in v2.0.

**Comment by CYTE2142** [comment] 2017-10-05 17:45
Hey Jonathan, 
wow, everything was already scaled 1,1,1, rotations and transforms were zeroed....but nevertheless your tip made it work! thanks a ton! the addon rocks! in looking forward to the next version.

Cheers and thanks for the quick reply
Philipp

**Closed** 2020-12-02 17:23 UTC
