### ISSUE TITLE
Strokes tool causes exception and weird faces after closing message. 

### ISSUE THREAD

**Issue by JohnRudy** [CGCookie/retopoflow#722] opened 2019-05-17 08:42 UTC
https://imgur.com/a/d0W1Qqt Screenshots of the process. 

Trying to create a single edge causes a error message. 

```
Environment:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1080/PCIe/SSE2, 4.6.0 NVIDIA 425.31, 4.60 NVIDIA
- Timestamp: 2019-05-17 11:41:37.605184
- Undo: extrude strip, extrude strip, select, select all, create strip, select all, select, select all, select, select all

Error Hash: e83bafdafdb8bf2c2e7f6a3b58409343

Trace:

- EXCEPTION (<class 'ValueError'>): vert_splice(...): verts can't share a face
- .../rfmode\rfmesh_wrapper.py
- 000 0194:merge() vert_splice(bmv1, bmv0)
- .../rfmode\rftool_strokes.py
- 001 0699:extrude_strip() b.merge(a)
- .../rfmode\rftool.py
- 002 0076:wrapper() ret = fn(*args, **kwargs)
- .../rfmode\rftool_strokes.py
- 003 0261:stroke() if self.replay: self.replay()
- .../rfmode\rfwidget_brushstroke.py
- 004 0056:modal_brushstroke() if self.stroke_callback: self.stroke_callback()
- .../rfmode\rfwidget.py
- 005 0189:modal() nmode = self.FSM[self.mode]()
- 006 0194:modal() raise e
- .../rfmode\rfcontext.py
- 007 0579:modal_main() if self.rfwidget.modal():
- 008 0496:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment] 2019-05-17 09:46
Thanks for the report, @JohnRudy.  That is a strange error.  Are you able to replicate this bug again?  If so, would you mind sharing your .blend file, because I'm having trouble reproducing the same conditions here.

**Comment by JohnRudy** [comment] 2019-05-17 10:06
> Thanks for the report, @JohnRudy. That is a strange error. Are you able to replicate this bug again? If so, would you mind sharing your .blend file, because I'm having trouble reproducing the same conditions here.

I can try. I all ready moved past the issue in the main .blend so that is not an option. I'll make a quick redo with a different blend.

**Comment by JohnRudy** [comment] 2019-05-17 10:16
I was able to reproduce the error just using a sphere that I first subdivided to 200k+ and decimating it to ~30k.  I've attached the screenshot of the line I was trying to create. Using the Patches tool the face creates normally with no issues, but the stroke tool causes an error. The face is twisted. 
Screenshot and .blend file in my dropbox.
https://www.dropbox.com/sh/r0c2znkte1i88s6/AAB6LlJq9Tod3pBSQtm3ZUGHa?dl=0

**Comment by vxlcoder** [comment] 2019-05-27 15:25
Thanks for the details and the .blend file, @JohnRudy!

I think I have fixed this in branch issue/722.  If you can, please check it out and let me know.  If you need help with this, let me know.

**Comment by JohnRudy** [comment] 2019-05-27 15:44
I tried modifying the files with the added and removed lines, but I loose the strokes tool from the toolbar. Using the shortcut key ( I ) does not work either. I presume I did something wrong? I copied the new lines and removed the - marked ones.

**Comment by vxlcoder** [comment] 2019-05-27 16:02
Great!  thanks for testing it!  Will close the issue, but feel free to reopen if you find other related issues.

**Closed by vxlcoder** 2019-05-27 16:02 UTC
Labels: Ready for Testing, bug, tool: strokes
