### ISSUE TITLE
Guide mode crash

### ISSUE THREAD

**Issue by Gnuren** [CGCookie/retopoflow#105] opened 2015-03-27 20:34 UTC
Guide mode crashes quite frequently.
You can get a screencast of the problem occuring, a describtion and the .blend used from my dropbox:
https://www.dropbox.com/s/30cfxjq0f9xpc7j/Guide_mode_crash.zip?dl=0

**Comment by carter2422** [comment] 2015-03-30 14:17
Thanks for the report @Gnuren. I'm so far unable to replicate the issue here but I'll keep trying. 

Next time it crashes for you, could you take a screenshot of the error message and upload that here?

**Comment by Gnuren** [comment] 2015-03-30 14:53
I've already recorded a screencast of this happening. It's bundled in the zip from my dropbox.
The link is in my original post.
If you need a screenshot i post one later...

**Comment by carter2422** [comment] 2015-03-30 14:53
I've got the screencast, thanks for doing that. Additional screenshots, particularly of any other errors, would be helpful :+1:

**Comment by Gnuren** [comment] 2015-03-30 14:55
will do. Not able to do so for the next couple of hours, but hopefully later today/tonight

**Comment by carter2422** [comment] 2015-05-06 18:36
Any luck replicating the issue @Gnuren?

**Comment by Gnuren** [comment] 2015-05-06 19:26
Sorry, no.
Haven't had time to investigate further.
Feel free to ignore this for now...
when i find the time to do some blending again i will let you know if i can reproduce the issue.

**Comment by carter2422** [comment] 2015-05-06 19:30
No problem. I'll close the issue for now since we can't reproduce if. If you find a time to check it out and narrow down the issue then we can re-open then.

**Closed by carter2422** 2015-05-06 19:30 UTC
Labels: bug, tool: contours
