### ISSUE TITLE
[BUG] Starting Retopoflow on default cube catches exception.

### ISSUE THREAD

**Issue by hanetzer** [CGCookie/retopoflow#1312] opened 2024-04-04 23:35 UTC
Hello. I'm just giving RetopoFlow a go as an independent tinkerer who makes avatars for Chillout VR and wanna try some new stuff, so I've dl'd the version given in this repo's releases tab. I don't do commercial blender work as of this moment so I figured that'd be ok.

Retopoflow Version: RetopoFlow_v3.4.3-Github.zip or current git master `fd176f7441ac7658697456b754514fe3452e2b19`, cloned and symlinked to ~/.config/blender/4.0/scripts/addons/RetopoFlow

Blender Version/Hash: `media-gfx/blender-4.0.2::gentoo was built with the following:
USE="X bullet color-management cycles embree ffmpeg fftw fluid gmp jpeg2k nls oidn openexr openmp openpgl opensubdiv openvdb pdf potrace pugixml pulseaudio sdl sndfile tbb tiff wayland webp -alembic -collada -cuda -cycles-bin-kernels -debug -doc -jack -jemalloc -man -nanovdb -ndof -openal -optix -osl -test -valgrind" ABI_X86="(64)" PYTHON_SINGLE_TARGET="python3_11 -python3_10"`

Platform Version/Distribution: Gentoo Linux, updated as of ~few days ago.

**Issue:**

```
RetopoFlow: Initial load
RetopoFlow git: master fd176f7441ac7658697456b754514fe3452e2b19
RetopoFlow options path: /home/hanetzer/Projects/retopoflow/RetopoFlow_options.json
No options file
cgcookie addon: Verbose is enabled
cgcookie addon: Wrote out updater JSON settings with content:
cgcookie addon: {'last_check': '', 'backup_date': '', 'update_ready': False, 'ignore': False, 'just_restored': False, 'just_updated': False, 'version_text': {}}
CookieCutter_Exceptions: handling caught exception
    action: initialize internals (Exception Callbacks, FSM, UI, Actions)
____________________________________________________________________________________________________
Exception Info
- Time: 2024-04-04 18:25:22.351891
- Count: 1
- Hash: 73adc43638c083cd336d72b6d7a04e86
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'keys'
  -     .../common/useractions.py
  - 000 0264:kmi_to_op_properties() props = { k: kmi.path_resolve(f'properties.{k}') for k in kmi.properties.keys() }
  - 001 0347:__init__() action, op_props = kmi_to_action(kmi), kmi_to_op_properties(kmi)
  - 002 0312:get_instance() Actions._instance = Actions(context)
  - 003 0715:__init__() ActionHandler._actions = Actions.get_instance(context)
  -     .../common/ui_document.py
  - 004 0128:init() self.actions = ActionHandler(context, UI_Document.default_keymap)
  -     .../cookiecutter/cookiecutter_ui.py
  - 005 0081:_cc_ui_init() self.document.init(self.context)
  -     .../cookiecutter/cookiecutter_modal.py
  - 006 0087:modal_init_cc_internals() self._cc_ui_init()
  -     .../cookiecutter/cookiecutter_exceptions.py
  - 007 0036:try_exception() yield
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CookieCutter_Exceptions._callback_exception_callbacks: 'NoneType' object has no attribute 'keys'
RF_UI.handle_exception: 'NoneType' object has no attribute 'keys'
Info: Total files 3 | Changed 3 | Failed 0
Info: Saved "RetopoFlow_backup_EMERGENCY.blend"
CookieCutter caught exception while calling back exception callbacks: handle_exception
____________________________________________________________________________________________________
Exception Info
- Time: 2024-04-04 18:25:22.402906
- Count: 2
- Hash: ff771211a35cd47019b5e8c2c9dbd979
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'UI_Document' object has no attribute '_body'
  -     .../common/ui_document.py
  - 000 0169:body() return self._body
  -     /home/hanetzer/.config/blender/4.0/scripts/addons/RetopoFlow/retopoflow/rf/rf_ui_alert.py
  - 001 0323:alert_user() self.document.body.append_child(win)
  -     /home/hanetzer/.config/blender/4.0/scripts/addons/RetopoFlow/retopoflow/rf/rf_ui.py
  - 002 0064:handle_exception() self.alert_user(title='Exception caught', message=message, level='exception', msghash=h)
  -     .../cookiecutter/cookiecutter_exceptions.py
  - 003 0057:_callback_exception_callbacks() fn(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
GitHub: Not reported, yet
```

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- Install RetopoFlow
- Open blender in shell to get logs, default cube scene
- select cube, start retopoflow from active
- get the above listed exception, retopoflow menu in header vanishes, new object called RetopoFlow is created but nothing can be done with it.

{*attach any files needed to replicate the issue*}

**Comment by hanetzer** [comment] 2024-04-05 00:00
Further testing seems to indicate some form of conflict with another addon. I disabled everything that was third party and it works now. I'll collect a list of the addons I use and see if that helps.

**Comment by vxlcoder** [comment] 2024-04-05 00:02
good catch! yeah, that would be super helpful to know which other add-on RF starts causing problems with. thanks

**Comment by jfranmatheu** [comment] 2024-12-03 22:38
Closing this issue due to confirmed conflict with another add-on and lack of further user info on the matter. If more details become available, the issue can be reopened.

**Closed by jfranmatheu** 2024-12-03 22:38 UTC
Labels: addon conflict
