### ISSUE TITLE
vertex are invisible

### ISSUE THREAD

**Issue by skyebasta** [CGCookie/retopoflow#717] opened 2019-04-24 17:18 UTC
I can't see vertex when I am creating in Retopoflow mode, albeit I can see it in Edit mode.
![Zrzut ekranu 2019-04-24 o 19 17 55](https://user-images.githubusercontent.com/49953371/56679605-c1f28e00-66c5-11e9-8939-416eee2a08f5.png)

**Comment by carter2422** [comment] 2019-11-21 15:18
Hey @skyebasta, apologies for missing this. This issues is a duplicate of #576 and it's one that've so far been unable to track down or replicate. 

Closing as duplicate.

**Closed by carter2422** 2019-11-21 15:18 UTC
