### ISSUE TITLE
Can't access retopoflow

### ISSUE THREAD

**Issue by DrPepeR** [CGCookie/retopoflow#1307] opened 2024-03-06 00:45 UTC
**[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 4.0.0

Blender Version/Hash: 4.0

Platform Version/Distribution: windows 10

**Issue:**

Retopoflow 4 is invisible/does not exist on the blender header anymore
(Could there be a side panel / key to open the extension just in case something like this happens ?)

![05 March 2024 18 37 24 _(Unsaved)_-_Blender_4 0](https://github.com/CGCookie/retopoflow/assets/12982937/29d6fa8d-5237-4c55-b7a9-89e1bf9d8b4f)

Even disabling every addon and only having retopoflow enabled it does not appear.
![05 March 2024 18 40 03 _(Unsaved)_-_Blender_4 0](https://github.com/CGCookie/retopoflow/assets/12982937/f53a1717-a2c0-4a34-8f89-a797f7939f6e)
![05 March 2024 18 39 59 _(Unsaved)_-_Blender_4 0](https://github.com/CGCookie/retopoflow/assets/12982937/6acf9876-561a-4bfe-9de1-bda6ebe2e344)

**How to Reproduce:**

- Just open Blender, it happens on any save or new files.

**Comment by jlampel** [comment] 2024-03-06 00:56
Hi, this is a duplicate of https://github.com/CGCookie/retopoflow/issues/1306 

RetopoFlow 4 is a totally new experience, and the tools (just PolyPen for now since it's the first alpha) are now in the Edit Mode toolbar. It's suggested to use RetopoFlow 3.4.3 instead unless you're just testing it out.

**Closed by jlampel** 2024-03-06 00:56 UTC
