### ISSUE TITLE
Autodisable scene statistics

### ISSUE THREAD

**Issue by German-S** [CGCookie/retopoflow#1086] opened 2022-02-11 09:42 UTC
Hello.
When using the RetopoFlow plugin, the built-in scene statistics are sometimes autodisabled in Blender itself.
When me need to switch to Blender's edit mode, me often have to go into its settings menu to turn back the display of scene statistics, since it was disabled automatically after using the RetopoFlow plugin.

I could not find a description of this problem, how can I solve it?

**Comment by vxlcoder** [comment] 2022-02-11 18:17
thanks for the report, @German-S.

I will take a look at this.

**Comment by vxlcoder** [comment] 2022-03-03 03:58
I'm taking a closer look into this issue, @German-S, but I'm not able to reproduce it.

Can you give me some more details?

What version of RetopoFlow are you using?  Blender version?

Can you take screenshots of Blender before starting RF, while RF is running, and after RF quits so I can see what you see on your machine?

Thanks!

**Comment by German-S** [comment] 2022-03-06 18:25
> 

I'm terribly embarrassed, but I seriously tried to reproduce this problem, the way I had it before.
And I couldn't call it...
Most likely, there is some other condition under which this problem is worked out.
If I manage to encounter this problem again, I will try to reproduce it several times, and if I succeed, I will definitely let you know.

**Comment by vxlcoder** [comment] 2022-03-06 18:38
don't worry too much about it! we couldn't reproduce it either.

closing this for now, but do let us know if you have any other problems.

happy retopo'ing!

**Closed** 2022-03-06 18:39 UTC
Labels: can't replicate, need more info
