### ISSUE TITLE
not Updating from version 1.3 to 2.0

### ISSUE THREAD

**Issue by LearningThis** [CGCookie/retopoflow#434] opened 2018-03-04 11:01 UTC
Hihi have just purchased and installed and tried to update - however the Retopo version remains 1.3 and says addon is up-to-date ?- but its not 2.0, I have also checked for update and under the reinstall/install old version  i've closed and reopened blender I'm currently running blender v2.78.4
Thanks

**Comment by vxlcoder** [comment] 2018-03-04 18:27
Hi @LearningThis!

Thanks for the report, but version 2.0 is not released, yet.  We are still working on a few critical and difficult bugs and features.  Once we're comfortable that it is ready for use, we'll make it available to the public, and you should then see that update!  So, right now, version 1.3 is the latest stable version of RF.

In the meantime, you are free to test version 2.0 if you are familiar with downloading source from GitHub.  The `release/2.0.0` branch is the most recent version.  Just know that there will be issues and missing features.  If you do find a bug while testing 2.0, please report them so we can correct them!

Thanks again for the report, but I'm going to close it now since it's not a bug.

**Closed by vxlcoder** 2018-03-04 18:27 UTC

**Comment by LearningThis** [comment] 2018-03-04 18:30
So sorry Jon!
Maybe was too excited to read the small print
Congratulations on a wonderful plugin though
Am very much enjoying! Even as is it is amazing
No doubt 2.0 will be even more successful

Best of luck and many thanks!

**Comment by vxlcoder** [comment] 2018-03-04 18:46
No problem!  :)  glad RF is working well for you.  Do report any issues you have with it, and we'll do our best to get them fixed!
