### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by deock90** [CGCookie/retopoflow#1020] opened 2021-06-24 21:11 UTC
Environment:

- RetopoFlow: 3.2.0
- CG Cookie built
- Blender: 2.92.0 master 2021-02-24
- Platform: Windows, 10, 10.0.19041, AMD64, AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2070/PCIe/SSE2, 4.5.0 NVIDIA 466.77, 4.50 NVIDIA
- Timestamp: 2021-06-24 17:04:55.259455
- Undo: 

Error Hash: 524d26fc2c1d9b502c8db86e19029e05

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'name'
-     C:\Users\Deock\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rf\rf_ui_alert.py
- 000 0150:report() 'title': f'{self.rftool.name}: {title}',
-     .../common\ui_core.py
- 001 2014:<lambda>() callback = lambda e: old_callback()
- 002 2037:_fire_event() cb(details)
- 003 2043:_fire_event() raise e
- 004 2074:dispatch_event() self._fire_event(event, ui_event)
-     .../common\ui_document.py
- 005 0551:mousedown_exit() under_mouseclick.dispatch_event('on_mouseclick')
-     .../common\fsm.py
- 006 0058:run() return fn(*args, **kwargs)
![RetopoFlow_screenshot](https://user-images.githubusercontent.com/41754489/123332898-1ba5ab80-d50f-11eb-9d61-693e21ed4ab2.png)

**Comment by vxlcoder** [comment] 2021-06-24 21:13
thanks for the report, @deock90. will take a look

**Comment by NikRog991** [comment] 2021-06-25 14:14
I had the same issue, the report path led to this thread. I updated the add-on inside blender in the tab then had same error as here. Later I removed it from blender and installed it normally from zip download file. Now it works. Hope this helps with your issue.

**Comment by vxlcoder** [comment] 2021-08-01 20:07
@deock90, we have had a few reports of strange errors that were fixed after doing a fresh install of RetopoFlow, similar to @NikRog991's experience.

Please try that to see if it resolves your problems.  let me know if does not correct the issue for you.

**Comment by jlampel** [comment] 2021-08-18 17:39
This should be fixed in 3.2.2. It does require updating via a .zip file rather than from the updater since the issue was caused by the updater. If it happens again please let us know!

**Closed by jlampel** 2021-08-18 17:39 UTC
Labels: need more info

**Comment by SYNTAXDZ** [comment] 2021-09-14 13:07
i updated retopoflow from version 3.2.0 to 3.2.2 from the Updater system, and im getting this error, i solved that by installing the .zip version, **and you have to restart blender!**
