### ISSUE TITLE
Loops: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by indiegael** [CGCookie/retopoflow#844] opened 2020-06-10 13:32 UTC
Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β2
- Blender: 2.83.0 master 2020-06-03
- Platform: Windows, 10, 10.0.18362, AMD64, AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
- GPU: ATI Technologies Inc., AMD Radeon R9 200 Series, 4.5.13596 Core Profile Context 20.5.1 27.20.1017.1011, 4.60
- Timestamp: 2020-06-10 14:31:25.929775
- Undo: select, dissolve Loops, select smart, select, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move

Error Hash: 92f6c95acb0ce66e2f995f52070c055b

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMEdge has been removed
-     C:\Users\Gael\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0120:select() return self.bmelem.select
-     C:\Users\Gael\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rftool_loops\loops.py
- 001 0235:main() if self.hovering_edge.select: self.rfcontext.deselect(self.hovering_edge)
-     .../common\fsm.py
- 002 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment] 2020-06-29 13:56
This issue _should_ be fixed now, @indiegael.

I'm not entirely certain what steps you took to cause this error, so I cannot reproduce this error.  However, I put in checks to prevent this in the future.

Closing for now, but please reopen / create new issue if you run into it again.

Thanks!!

**Closed by vxlcoder** 2020-06-29 13:56 UTC
