### ISSUE TITLE
[BUG] Vertex normals are not normalized (they still seem to point into the direction of the surface they were placed on)

### ISSUE THREAD

**Issue by silkentrance** [CGCookie/retopoflow#1027] opened 2021-07-14 19:55 UTC
Retopoflow Version: 3.2.0

Blender Version/Hash: 2.93.1

Platform Version/Distribution: Windows 10, 21H1

**Issue:**

When exiting retopo mode, the normals are not recalculated and will give weird artifacts when baking normal maps.

So after I baked the normal maps using either TexTools or the standard render/bake, I get the following result

![image](https://user-images.githubusercontent.com/6068824/125682914-2239c29a-107f-41eb-9d06-ac185ee4e074.png)

With 3.2.0, one can simply enter edit mode and recalculate the outside normals and everything seems to be fine,
but it is still a PITA to go this workaround route.

So after fixing the normals, I then get this result after rebaking the normal map

![image](https://user-images.githubusercontent.com/6068824/125684199-42de6683-f39e-4824-b3ab-8caebaec1c89.png)

Which is still far from being perfect, modelling/retopology wise, but better nonetheless.

In version 3.1.0 this was even more prominent and unfix-able even, also when recalculating the outside normals, it seems as if the edge normals were also reversed in this version, giving you some weird creases on all edges of the so retopologized model.

**Comment by vxlcoder** [comment] 2021-07-14 19:59
thanks for the report, @silkentrance!

are you able to share a .blend file or steps to reproduce this bug?

we haven't seen this issue come up before, so i'm a little confused on how to reproduce this.

thanks!

**Comment by silkentrance** [comment] 2021-07-14 20:37
Since the information is being baked into the normal map, I will provide you with a blend file that contains only the non normalized (normals wise) version of the retopo.

I have reduced the high poly to a bare minimum but be advised that it might still be subject to licensing, although it was given to me during an online lecture in a course that I am currently taking. 

So in order to reproduce

1. bake the normal map from the high poly mesh unto the low poly mesh uv
2. see the artifacts
3. fix the normals on the low poly mesh
4. rebake the normal map
5. see the difference

There is a texture in the file called wrench_normal_tangent_artifacts that contains the artifacts (step 1) and a wrench_normal_tangent that does not contain the artifacts (step 4).

There is an object called RetopoFlow which represents the original object gotten from retopoflow and an object called Wrench.High which is said high poly scan model.

Also there is a Wrench.NonNormalized.Low object that should be equal to RetopoFlow but with a material based on wrench_normal_tangent_artifacts and a version of it called Wrench.Normalized.Low with recalculated normals and the so corrected material wrench_normal_tangent.

However, blender seems to fix things up when loading the file and the issue will be gone, so you will have to reproduce it yourself from the RetopoFlow object.

**Comment by silkentrance** [comment] 2021-07-14 20:39
so it seems it is with the model rather than the baked normals map.

**Comment by vxlcoder** [comment] 2021-07-14 20:45
awesome!  thank you!

**Comment by silkentrance** [comment] 2021-07-14 20:49
hmpf, blender, you might want to rebake the normal map for both the normalized and the non normalized, which gives me the exact same result as depicted in the issue description.

**Comment by vxlcoder** [comment] 2021-07-14 20:56
ok. i tried recreating your low-res mesh (hid everything, revealed `Wrench.High`), started new target at active, and used PolyPen to create something that resembles your low res version.  but the normals produced during my session seem to be fine (pointing outwards like they should).

![image](https://user-images.githubusercontent.com/3790699/125691155-250399e7-616f-484f-879d-04db7e18fc30.png)

interestingly, though, going back into RF on my mesh and using the recalculate normals button (under target cleaning), the normals get flipped to inside the high res mesh.

![image](https://user-images.githubusercontent.com/3790699/125691458-ecdcb35b-c4e1-47b9-b673-abcc0e1e9281.png)

is the latter the issue that you're running into?

i also noticed that the vertex normals and face normals aren't staying in sync (sometimes the vert normals are outward but face normals are still inward)... i wonder if that could be a problem, too.

**Comment by silkentrance** [comment] 2021-07-14 20:58
Hm, I did not use flip or recalculate, but I used snap and merge by distance.

**Comment by vxlcoder** [comment] 2021-07-14 21:02
yes, snap (with distance of 0) caused the vert and face normals to point opposite.

about:

> No for the example I did not use any of these tools.

if you use PolyPen to create the low res version again---without using any other tool or clean-up features (such as snap, merge, recalculate, flip)---do you get the correct results?

i'm wondering if the issue lies with the tools creation of geometry, or in the clean-up features.

thanks for helping me debug this!

**Comment by silkentrance** [comment] 2021-07-14 21:03
okay will redo the whole shebang.

**Comment by silkentrance** [comment] 2021-07-14 21:06
i do use move 'G' vertices/edges/faces a lot.

**Comment by silkentrance** [comment] 2021-07-14 21:12
without moving any verts using G the result is ok.

**Comment by vxlcoder** [comment] 2021-07-14 21:12
using G with PolyPen, yes?

**Comment by silkentrance** [comment] 2021-07-14 21:13
yes, and the tweak tool

**Comment by vxlcoder** [comment] 2021-07-14 21:14
ok.  that's a good place to start looking for the problem!  will take a closer look at how those tools update the normals, and check in on the vert-face normal issue mentioned before.

will ping you back once i've found something to test out, etc.

thank you for your help!

**Comment by silkentrance** [comment] 2021-07-14 21:17
hm, I am no longer able to reproduce the issue, although I reproduced it when creating the example.blend file. weird issue.

**Comment by silkentrance** [comment] 2021-07-14 21:21
great, looking forward to hearing from you again soon.

**Comment by vxlcoder** [comment] 2021-07-15 19:13
@silkentrance, i _think_ commit 79892b7 will fix your issue, but i might have missed some code paths that update normals.

if you want to test, you can download that commit specifically or download branch `v3.2.1` using the add-on updater (see [link](https://docs.retopoflow.com/addon_updater.html) for details).  if this doesn't fix it, let me know what all tools and operations you recall using (ex: G with PolyPen, the recalculate face normals button under options > target cleaning, tweak brush, relax, etc.) and I'll check those code paths.

Thanks!

**Comment by silkentrance** [comment] 2021-07-16 11:21
Thank you very much for the quick response!

Okay, I redid the retopo of the high poly mesh bit and here is what I found out:

- using the strokes tool i drew an outline of the inner part of the bevel/crease, i then drew a second outline around that at near the top of the bevel
- i then used the polypen tool to fill in the missing faces on the inside of the first stroke
- i then copied the mesh and used textools to bake the normal map from high to low
- as you can see the normal map is still off around the edges of the inner bevel/crease

![image](https://user-images.githubusercontent.com/6068824/125939967-ae166472-16ca-4c3f-9186-2ba4d0e5e59d.png)

- using recalculate from target cleaning did not fix the issue for me
- mesh/normals/recalculate outside however did do the trick

**Comment by silkentrance** [comment] 2021-07-16 11:38
I will try a retopo using standard tools and compare that to the result above

**Comment by vxlcoder** [comment] 2021-07-16 11:39
thanks you for testing this again!

will check out the code once more...

**Comment by vxlcoder** [comment] 2021-07-16 11:42
another thing I'll need to consider is that RetopoFlow computes normals slightly differently for face than blender. the vertex normal depends on the normal of the surface it snaps to. will see just his different these are.

**Comment by silkentrance** [comment] 2021-07-16 11:43
I wonder if someone else had this problem, too. perhaps something in my workflow is wrong?

**Comment by vxlcoder** [comment] 2021-07-16 12:26
one note: the normal map is built with respect to the normals of mesh. so even if normals might be "off" on low res and normal map, the end result will still look the same because they "work with each other" to do the right thing.

**Comment by vxlcoder** [comment] 2021-07-16 12:36
(at least, in theory that's correct :) )

**Comment by silkentrance** [comment] 2021-07-16 13:14
Just did a new retopo using also the knife tool.

The normals (without any recalculation applied) look just fine. Wonder what is the problem here.

![image](https://user-images.githubusercontent.com/6068824/125953615-e9d509a3-741f-4bee-9fe1-3cf6467b61f9.png)

**Comment by silkentrance** [comment] 2021-07-16 13:52
just did a standard retopo (snap faces/project individual elements, mirror modifier, shrinkwrap modifier) and it gives me the same result, still some artifacts on the edges (ragged, somewhat beveled rendering).
it seems that it is an issue with the high res model i am using which uses just tris.

**Comment by silkentrance** [comment] 2021-07-16 14:01
however, your proposed fix fixed issues with the inner edges and verts, which looked really bad, now it gives me the same result as the standard retopo workflow.

great!

**Comment by vxlcoder** [comment] 2021-07-16 14:03
good to hear!

thanks for digging into this. I haven't spent too much time testing RF + normal baking, so this is helpful.

let me know if you find anything else peculiar.

**Comment by jlampel** [comment] 2021-07-26 18:40
It sounds like creating a mesh in RetopoFlow now matches creating a mesh in edit mode when it comes to normals and baking, so I'll close this out. If there are any other problems with that workflow, please let us know!

**Closed by jlampel** 2021-07-26 18:40 UTC
Labels: Ready for Testing

**Comment by silkentrance** [comment] 2021-07-26 19:20
Thank you!
