### ISSUE TITLE
BUG - Undo not working - Retopoflow 3.2.0

### ISSUE THREAD

**Issue by eighttony** [CGCookie/retopoflow#1033] opened 2021-07-29 16:44 UTC
**[BUG]**

Retopoflow Version: {*3.2.0*}

Blender Version/Hash: {*2.92.0*}

Platform Version/Distribution: {*Windows 10*}

&nbsp;

**Issue:**

{*Hello, 
recently purchased the retopoflow addon and after testing it a few times I always had the same issue that the undo function is not working at all once I switched to the retopoflow mode. 

Already updated the latest version (I think it is the latest one?) and still not able to undo my steps.
Also should mention I am using a German keyboard and changed the 'undo' shortcut to a custom one: Ctrl + <
*}

{*add any screenshots of the issue here*}
![undo_not_working](https://user-images.githubusercontent.com/88156397/127531743-29838d88-8d0a-447f-8102-971ad49b6fe7.JPG)

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment] 2021-07-29 17:43
thanks for the report, @eighttony!

will take a look at this as soon as possible.

in the mean time, maybe try using the keymap editor ([doc](https://docs.retopoflow.com/keymap_editor.html)) to change the undo/redo buttons to something that works for your keyboard/setup.  if you get it working, please share here what you ended up using (maybe include a screenshot of the keymap editor, too)

**Comment by eighttony** [comment] 2021-07-31 07:55
@vxlcoder thanks for the quick reply Jon. 

I checked the link you added/documentation and tried to find the 'undo' option in the keymap editor inside retopoflow but sadly I couldn't find the option there to change the undo shortcut to another key tho. 

So I changed the undo shotcut inside Blender itself but getting the same issue that it is not working...

**Comment by vxlcoder** [comment] 2021-08-01 20:03
ah, @eighttony, i didn't see the `GRLESS` in your blender keymap, and I forgot that we use whatever Blender uses without overrides (so undo, redo, and save all are not on RF keymap editor).  doing a little research, it seems that blender supports it ([somewhat](https://developer.blender.org/T64004)), but there are other keys that are not yet handled ([link](https://developer.blender.org/D7204), [list of all supported keys](https://docs.blender.org/api/current/bpy.types.Event.html)).

commit b49377d _might_ fix this issue, but i don't have a keyboard with this key to test it (simply using keyboard layout will not work).

if you have time, would you mind testing this out to see if it works?  use this [doc](https://docs.retopoflow.com/addon_updater.html) to update RetopoFlow to branch `v3.2.1` to give it a go.

thanks!

**Comment by vxlcoder** [comment] 2021-08-11 11:48
thanks for the update, @eighttony.

just to be clear: you did update to RetopoFlow 3.2.1?

**Comment by vxlcoder** [comment] 2021-08-11 11:52
a few things:

- we have had a few people report that the updater wasn't working perfectly.  if you could, try uninstalling RF, restart blender, then install the latest version (v3.2.1) from zip.
- did you restart Blender after changing the undo shortcut, then tried undoing in RF?
- what shortcut did you try using for blender's undo?

**Comment by eighttony** [comment] 2021-08-17 07:58
@vxlcoder 
what I did:
- uninstalled Blender and reinstalled Blender 2.93 + I did restart Blender after changing the shortcut.
- tried the updater (and as you mentioned) it didn't work properly so I manually uninstalled and reinstalled RF
- changed the shortcut from CTRL + GRLESS to CTRL + Z (even tried SHIFT + Z) - nothing worked for me. 

I could see and give it another try maybe...

**Comment by vxlcoder** [comment] 2021-08-17 14:38
thank you @eighttony.  I'm working to debug this issue with another developer who has a german keyboard with GrLess key.  Hopefully the turn-around time will be shorter, and we'll get a _working_ solution sooner.  thanks for your patience and assistance!

**Comment by vxlcoder** [comment] 2021-08-17 14:49
Ok, @eighttony.  The other developer just tried it on his system, and both `Ctrl+GrLess` and `OsKey+GrLess` worked to undo changes in RetopoFlow on his machine.

I think that the issue is actually fixed, but that the addon updater is broken so you aren't seeing getting that fix correctly.

Can you try installing RF from this zip: https://www.dropbox.com/s/8l6i0q9ix373zje/RetopoFlow_v3.2.2-alpha.zip?dl=0

note: this link is only temporary for now, but it is the exact zip that the other dev used to run tests.

**Comment by eighttony** [comment] 2021-08-19 07:10
hi @vxlcoder so I checked out the Blender Preferences - Keymap tap again and tried changing the keymap list from my custom: t8 blender keymaps to the default 'Blender' keymap function. 

Within the 'Blender' keymap list I changed the 'undo' key to Ctrl+GrLess and surprisingly the undo function works just fine now in RF! 

Guess it's due to the change of the keymap list... 
anyway now the undo function is working. 
![blender_keymap](https://user-images.githubusercontent.com/88156397/130024132-71136132-1c26-4b94-a649-55dcb839d1b3.JPG)

**Comment by vxlcoder** [comment] 2021-08-19 10:44
glad to hear undo is working now!

if you'd like, you can export the t8 keymap and attach it here so I can take a closer look at that.

or, if you're satisfied that your issue is resolved, I can just close this issue.

I appreciate your help in getting this fixed (for you as well as for all other customers).  thank you!

happy retopo'ing!

**Comment by vxlcoder** [comment] 2021-08-19 13:53
closing this issue for now.  please reopen if you continue to have issues.

**Closed by vxlcoder** 2021-08-19 13:53 UTC
Labels: help wanted, Ready for Testing, can't replicate

**Comment by Chreas** [comment] 2024-10-22 13:48
Here's the Crash Details if this helps:

Environment:

- RetopoFlow: 3.4.3
- Build: CG Cookie built for GitHub
- Blender: 4.02.0 blender-v4.2-release 2024-07-16
- Platform: Darwin, 23.6.0, Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:52 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6020, arm64, arm
- GPU: {'backend': 'METAL', 'device': 'APPLE', 'vendor': 'Apple M2 Max', 'renderer': 'Metal API', 'version': '1.2', 'compute_shader_support_get': True, 'hdr_support_get': True, 'max_batch_indices_get': -2147483648, 'max_batch_vertices_get': -2147483648, 'max_images_get': 128, 'max_texture_layers_get': 2048, 'max_texture_size_get': 16384, 'max_textures_frag_get': 128, 'max_textures_geom_get': 0, 'max_textures_get': 128, 'max_textures_vert_get': 128, 'max_uniforms_frag_get': 1024, 'max_uniforms_vert_get': 1024, 'max_varying_floats_get': 60, 'max_vertex_attribs_get': 31, 'shader_image_load_store_support_get': True}
- Timestamp: 2024-10-22 15:46:49.685221

Runtime:

- Undo: cut, cut
- Error Hash: d0d7bef2afdc0c76880bbf2eceedc7b5

Trace:

- EXCEPTION (<class 'ReferenceError'>): StructRNA of type Object has been removed
-     /Users/frederic/Library/Application Support/Blender/4.2/scripts/addons/RetopoFlow/retopoflow/rfmesh/rfmesh.py
- 000 0253:get_obj_name() return self.obj.name
-     /Users/frederic/Library/Application Support/Blender/4.2/scripts/addons/RetopoFlow/retopoflow/rf/rf_sources.py
- 001 0102:get_rfsource_snap() n = rfsource.get_obj_name()
- 002 0113:raycast_sources_Ray() if not self.get_rfsource_snap(rfsource): continue
- 003 0133:raycast_sources_Point2D() return self.raycast_sources_Ray(self.Point2D_to_Ray(xy, min_dist=self.drawing.space.clip_start), correct_mirror=correct_mirror, ignore_backface=ignore_backface)
- 004 0140:raycast_sources_mouse() return self.raycast_sources_Point2D(self.actions.mouse, correct_mirror=correct_mirror, ignore_backface=ignore_backface)
-     /Users/frederic/Library/Application Support/Blender/4.2/scripts/addons/RetopoFlow/retopoflow/rf/rf_fsm.py
- 005 0099:update() self.actions.hit_pos,self.actions.hit_norm,_,_ = self.raycast_sources_mouse()
-     .../cookiecutter/cookiecutter_modal.py
- 006 0143:modal_mainloop() self.update()
-     .../cookiecutter/cookiecutter_exceptions.py
- 007 0036:try_exception() yield
