### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Cyroneradurna** [CGCookie/retopoflow#913] opened 2020-12-04 05:22 UTC
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

Using Polypen to create a loop around a kneecap.

{*add any screenshots of the issue here*}
![image](https://user-images.githubusercontent.com/44145780/101125161-30940f00-35be-11eb-83f6-024470655108.png)

Use polypen to try and create a loop.  Setting I used was also to create only quads instead of the create tris/then quads setting.  The result is just the edge you see in the above screenshot

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.1
- CG Cookie built
- Blender: 2.91.0 master 2020-11-25
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce RTX 2060/PCIe/SSE2, 4.5.0 NVIDIA 457.30, 4.50 NVIDIA
- Timestamp: 2020-12-03 23:15:01.011992
- Undo: insert, insert, select, move after select, grab, select, insert, grab, select, move after select

Error Hash: 2a1de537f6e24d10f04e9a321bd0667e

Trace:

- EXCEPTION (<class 'ValueError'>): edges.new(): this edge exists
-     C:\Users\ajvic\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh.py
- 000 1524:new_edge() bme = self.bme.edges.new(verts)
-     C:\Users\ajvic\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rf\rf_target.py
- 001 0470:new_edge() return self.rftarget.new_edge(verts)
-     C:\Users\ajvic\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool_polypen\polypen.py
- 002 0565:_insert() e1 = self.rfcontext.new_edge([bmv2, bmv3])
-     C:\Users\ajvic\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 003 0141:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\ajvic\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool_polypen\polypen.py
- 004 0365:insert() return self._insert()
-     .../common\fsm.py
- 005 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment] 2020-12-04 13:50
Thanks for the report, @Cyroneradurna.  will take a look

**Comment by Cyroneradurna** [comment] 2020-12-05 01:19
No problem @vxlcoder !  I wanted to add something else as well since I was able to reproduce the problem exactly last night repeatedly.  Using the Polypen tool I usually try to create the loops first in open geometry like i showed in the screenshot, but i only get the error when trying to create the points and using the program to fill it, which is why it left that open edge and point, and it only happened on the lower right hand corner.  To get around the issue, I had to create the other geometry around it first and then fill it.  I added a screenshot to help show as well.  
![image](https://user-images.githubusercontent.com/44145780/101229340-5cb69b00-3665-11eb-988f-4361e03c3522.png)  

Thank you once again, I love this tool and I want to help you in further fixing and developing it so I'll continue to try and report bugs as best as I can when they pop up for you.

**Comment by vxlcoder** [comment] 2020-12-15 20:13
i was not able to reproduce your bug, but i know where it is happening and why.  i've added a quick check in commit e2a1c13 that only creates an edge if it does not already exist.  if you can test this, please let me know, otherwise it will go out in the next minor release.  Thanks for the report, @Cyroneradurna!

**Comment by jlampel** [comment] 2020-12-21 22:49
Closing this out as it appears to be fixed in the latest version. If it happens again, please let us know!

**Closed by jlampel** 2020-12-21 22:49 UTC
Labels: Ready for Testing, tool: polypen
