### ISSUE TITLE
Symmetry not wrapping correctly, and center is coming outwards

### ISSUE THREAD

**Issue by brandoirl** [CGCookie/retopoflow#1349] opened 2024-11-24 22:45 UTC
Retopoflow Version: 3.4.3

Blender Version/Hash: 4.2

&nbsp;

I am just starting to use retopoflow and am new to blender in general, however I have come across an issue which seems to not be present in the video, when I used the symmetry tool on the head model anything in the center starts coming outwards and a lot of the topology seems to not actually be wrapping around the model like how it is in the youtube video. I havent touched any settings and everything should be on default, so I am not sure what I am doing wrong or how to fix the issue, pictures are included demonstrating the issue.
![retopoflow](https://github.com/user-attachments/assets/e3a52fd5-8bfb-443d-956e-307a8b759543)
![retopoflow2](https://github.com/user-attachments/assets/4f8b3b7c-6a5c-441b-b547-e062014ee0c3)
![retopoflow3](https://github.com/user-attachments/assets/fd9d6dce-9fd9-4703-86f6-e9a4c76077bf)

&nbsp;

**How to Reproduce:**

I don't have many steps on how to reproduce, it is the first time I'm using the tool and it is causing this issue just by trying to do as instructed in the youtube video.

**Comment by vxlcoder** [comment] 2024-11-24 22:57
Thanks for the report, @brandoirl.

This is the first time I have seen this type of issue.

Would you mind sharing your .blend file with us?  you can post it here or send to retopoflow@cgcookie.com.

thanks!

**Comment by brandoirl** [comment] 2024-11-24 23:41
Sure I emailed it to you just now, the blend file said it was not supported when I tried to upload it here

**Comment by brandoirl** [comment] 2024-11-24 23:51
Sorry I only sent 1 of 2 blend files in the first email, so I sent a follow up email as well

**Comment by brandoirl** [comment] 2024-11-24 23:51
@vxlcoder Sorry I only sent 1 of 2 blend files in the first email, so I sent a follow up email as well

**Comment by vxlcoder** [comment] 2024-11-25 00:55
I tried reproducing your issues here, but I'm not getting the same results as you.

Now, I did get a few strange results, but my results are very different.

for example, when I used PolyStrips around the chin, one vert snapped to a surface inside the mouth rather than on the outside.

![image](https://github.com/user-attachments/assets/98380d15-726f-4b50-8c1c-dd1ec25811e1)

And when I stroked across the bridge of nose, I got some bunched up verts that were basically at the surface but not very neat.  Although, one point is definitely inside the mesh.

![image](https://github.com/user-attachments/assets/ab6608ee-1436-443a-9aaf-a224f5d38d47)

I think both of these issues (and perhaps your issue) all stem from the way we implemented symmetry, which works under normal circumstances, but seems to be having lots of problems with your mesh.

As a workaround, I found that scaling up the source (`C zm_Morph`) by 100x can sometimes help RetopoFlow work a bit better.

We are currently focusing on RF4, which will be a regular edit mode tool, so this particular symmetry issue will likely go away.  I'll take another look at this when RF4 is out.

**Comment by brandoirl** [comment] 2024-11-25 01:49
@vxlcoder did you try the other heads in the second blender file?
Also for now I just upscale the model? 
About RF4, is that right around the corner or should I be using the upscale solution until then?

**Comment by brandoirl** [comment] 2024-11-25 01:57
@vxlcoder did you try the other heads in the second blender file? I am getting similar results with them as well.
Also for now I just upscale the model? 
About RF4, is that right around the corner or should I be using the upscale solution until then?
What I did to come up on the problem was just use the poly strips until the center:
![retopoflow4](https://github.com/user-attachments/assets/398e219b-6267-4b0b-8972-2b9934e0f7cb)
![retopoflow5](https://github.com/user-attachments/assets/d13dacac-9584-47f9-a1df-cd3622bcd547)

**Comment by vxlcoder** [comment] 2024-11-25 01:59
oh!  i think the issue might be with the automerge.  try setting the threshold to a smaller number, like 0.0001.

![image](https://github.com/user-attachments/assets/39501c27-d928-4eeb-ac0a-743d1c130318)

**Comment by brandoirl** [comment] 2024-11-25 02:02
Ah awesome! That definitely seems to be getting me a lot better results at a quick try! Hopefully this should solve the issue entirely, if anything changes I'll update you. Thank you very much!

________________________________

**Comment by vxlcoder** [comment] 2024-11-25 02:06
glad to hear!  closing this issue for now, but feel free to reopen or start a new issue if you have any other problems.

happy retopoing!

**Closed by vxlcoder** 2024-11-25 02:06 UTC
