### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Blukael** [CGCookie/retopoflow#1237] opened 2023-06-26 10:20 UTC
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.3.0
- Self built
- Blender: 3.04.1 blender-v3.4-release 2022-12-19
- Platform: Windows, 10, 10.0.22621, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, Quadro P4200/PCIe/SSE2, 4.5.0 NVIDIA 536.23, (no shader version)
- Timestamp: 2023-06-26 12:20:08.049968
- Undo: move grabbed, select, move grabbed, select, move grabbed, select, move grabbed, select, move grabbed, select

Error Hash: d6de869d029aa5c4747e63d5c42f4f1b

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
-     C:\Users\s_12353_gameart\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0182:pinned() return bool(self.bmelem[self.rftarget.layer_pin])
- 001 0166:co() if options['pin enabled'] and self.pinned: return
-     C:\Users\s_12353_gameart\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\RetopoFlow\retopoflow\rf\rf_target.py
- 002 0582:set2D_vert() vert.co = xyz
-     C:\Users\s_12353_gameart\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\RetopoFlow\retopoflow\rftool_polypen\polypen.py
- 003 0710:modal_move() set2D_vert(bmv, xy_updated)
-     .../common\fsm.py
- 004 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment] 2023-06-26 15:39
thanks for the report, @Blukael!

i was not able to reproduce this issue, but I wrote some checking code that _should_ catch this issue.

**Comment by vxlcoder** [comment] 2023-07-01 20:38
closing this issue for now, but reopen if the issue persists.

thanks!

**Closed by vxlcoder** 2023-07-01 20:38 UTC
Labels: bug, Ready for Testing, can't replicate
