### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by henbull** [CGCookie/retopoflow#1126] opened 2022-05-30 04:05 UTC
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.6
- Self built
- Blender: 3.00.0 master 2021-12-02
- Platform: Windows, 10, 10.0.19043, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 497.29, (no shader version)
- Timestamp: 2022-05-30 14:05:33.708694
- Undo: insert, insert, insert, insert, insert, insert, insert, insert, insert, select

Error Hash: 341a534fc48cda28332a0fb00743a99f

Trace:

- EXCEPTION (<class 'PermissionError'>): [WinError 5] Access is denied: 'L:\\PROJECTS\\Ampol - 19261\\04 Post Production\\03 VFX and Animation\\3D\\Rnd\\Assets\\KiaRetopo\\KiaRetopo_v002_RetopoFlow_AutoSave.blend1'
-     C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\retopoflow-master\retopoflow\rf\rf_blendersave.py
- 000 0169:save_backup() if os.path.exists(filepath1): os.remove(filepath1)
- 001 0140:handle_auto_save() self.save_backup()
-     C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\retopoflow-master\retopoflow\rf\rf_states.py
- 002 0418:modal_main_rest() self.handle_auto_save()
- 003 0388:modal_main() return self.modal_main_rest()
-     .../common\fsm.py
- 004 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment] 2023-06-01 17:40
Ha!  over a year later and I'm finally getting around to replying to this issue.... so sorry that it's been so long!

You were getting this issue, because a previous blend file exists but cannot be deleted.  The report does not contain much detail on your system (by design for some security), so I cannot tell exactly why you're running into this issue.

In later versions of RetopoFlow, the error is much more gracefully handled and reported to you.  I see you were running Blender 3.0, but you should still be able to run RF 3.3.0.  If you can update to Blender 3.4+, you can try RF 3.4.0 when it's ready for release (any day now!).

Closing this issue for now, but please let us know if you continue to have issues.  I will do my very best to respond _before_ another year passes again.... *sigh*  Thanks for the report!

**Closed by vxlcoder** 2023-06-01 17:40 UTC
