### ISSUE TITLE
Navigation fails when Blender language is anything but English

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#649] opened 2018-10-27 16:24 UTC
This is a known issue but one that's becoming more important that we solve.

If the user has chosen anything other than default for Blender's interface language then most, if not all hotkeys fail when RetopoFlow is active.

**Comment by vxlcoder** [comment] 2018-11-25 17:18
duplicate of issue #593, which has been fixed.  closing!

**Closed by vxlcoder** 2018-11-25 17:18 UTC
Labels: !Priority, bug, duplicate
