### ISSUE TITLE
problem when activating retopoflow 2.0 in blender 2.79b (ubuntu18.04)

### ISSUE THREAD

**Issue by virgoss** [CGCookie/retopoflow#650] opened 2018-10-28 12:24 UTC
Hello to everyone!
When I try to activate retopoflow2.0 on Blender2.79b (ubuntu 18.04), this window opens. What can I do to solve the problem?
Thankyou.
![schermata da 2018-10-27 20-17-38](https://user-images.githubusercontent.com/5464370/47615779-2be20000-dab4-11e8-8d89-14f5fbdc8eaf.png)

**Comment by carter2422** [comment] 2018-11-01 13:22
@virgoss are you running a custom build of Blender or Daily Build? It seems the daily builds aren't being distributed with the `numpy` library, which is required for RetopoFlow (and many other add-ons). 

Please try activating in an official version of blender 2.79b from blender.org.

This is related, or a duplicate of #651

**Comment by carter2422** [comment] 2019-11-21 17:36
Closed for inactivity.

**Closed by carter2422** 2019-11-21 17:36 UTC
Labels: bug, need more info
