### ISSUE TITLE
Contours: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by akosszeki** [CGCookie/retopoflow#666] opened 2018-11-26 10:49 UTC
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1060 with Max-Q Design/PCIe/SSE2, 4.6.0 NVIDIA 388.75, 4.60 NVIDIA
- Timestamp: 2018-11-26 11:46:39.385377


Error Hash: 50ad1aa17c2cc9ca94e14a9a237bc6ff


Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
- .../rfmode\rfmesh_wrapper.py
- 000 0150:co() self.bmelem.co = self.symmetry_real(co, to_world=False)
- .../rfmode\rftool_contours.py
- 001 0399:modal_move() verts[i].co = p
- .../common\profiler.py
- 002 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- 004 0110:modal() nmode = self.FSM[self.mode]()
- 005 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 006 0556:modal_main() self.tool.modal()
- 007 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by akosszeki** [comment] 2018-11-26 10:51
I was using contours for retopology of a sheep's front feet from the front view.

**Comment by vxlcoder** [comment] 2018-11-26 13:48
Thanks for the report, @akosszeki.

Can you post a screenshot of what you were working on?  I'm trying to figure out how to reproduce this issue, but I cannot determine how it happened, yet.

**Comment by vxlcoder** [comment] 2018-11-26 13:50
I think this issue _should_ be fixed in `release/2.0.1` branch, but I want to make sure.  Thanks!

**Comment by akosszeki** [comment] 2018-11-26 16:06
The sheep's two legs could have caused the issue. They overlap in front
view.  But after the crash, it was working fine. I couldn't reproduce it
neither.

Jon Denning <notifications@github.com> ezt írta (időpont: 2018. nov. 26.,
H, 14:50):

**Comment by vxlcoder** [comment] 2018-11-29 02:04
I have tested all I could and was not able to reproduce this issue. I'm closing this issue, but feel free to reopen if it still happens. Thanks!

**Closed by vxlcoder** 2018-11-29 02:04 UTC
Labels: Ready for Testing, bug, can't replicate, tool: contours
