### ISSUE TITLE
Loops: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by Nit-Pick** [CGCookie/retopoflow#496] opened 2018-06-15 04:39 UTC
![retopoflow_screenshot](https://user-images.githubusercontent.com/9891501/41450110-2d9b1c5e-702b-11e8-98f9-6b9aac7eefca.png)

Right, so I was trying to make some testing avatar for VRChat, I made a boolean merge with a sphere and a subdivided cube. ~~~Now I don't know what I was pressing, but the error just happened when I was pressing something on the keyboard because I was trying to use the old shortcuts. If that wasn't it, I think I was trying to create loops the way it used to be, like mouse dragging or something.~~~ I left clicked and the same message popped up

-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.0

- EXCEPTION (<class 'UnboundLocalError'>): local variable 'sel_only' referenced before assignment
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rftool_loops.py
- 000 0110:modal_main() if sel_only: self.rfcontext.deselect_all()
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rftool.py
- 001 0103:modal() nmode = self.FSM[self.mode]()
- 002 0107:modal() raise e
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rfcontext.py
- 003 0472:modal_main() self.tool.modal()
- 004 0396:modal() nmode = self.FSM[self.mode]()

**Comment by vxlcoder** [comment] 2018-06-26 14:46
Thanks for the report, @Nit-Pick!
Will take a look at it soon.

**Comment by vxlcoder** [comment] 2018-07-03 22:49
Thanks for the report!  This is a duplicate of issue #461, which has already been fixed.  You can get the fix by pulling the latest commit of branch `release/2.0.0` or waiting just a few more days for the RF 2.0 Beta 2 release.  Closing for now.

**Closed by vxlcoder** 2018-07-03 22:49 UTC
