### ISSUE TITLE
PolyStrips: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by kudamuchi** [CGCookie/retopoflow#523] opened 2018-07-13 18:26 UTC
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0 beta 2
- Blender: 2.79.5 master 2018-07-07
- Platform: Windows, 10, 10.0.16299, AMD64, Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- GPU: Intel, Intel(R) HD Graphics 4000, 4.0.0 - Build 10.18.10.4425, 4.00 - Build 10.18.10.4425


Error Hash: 8ac2d1d979ba7c08b61f87125aff37e1


Trace:

- EXCEPTION (<class 'TypeError'>): 'NoneType' object is not subscriptable
- .../rfmode\rftool_polystrips.py
- 000 0160:add_strip() bmf1 = strip[-1]
- 001 0169:update() if not edge3: add_strip(bme3)
- 002 0081:start() self.update()
- .../rfmode\rfcontext.py
- 003 0299:set_tool() self.tool.start()
- .../rfmode\rfcontext_ui.py
- 004 0453:set_selected_tool() self.set_tool(rft.rft_class())
- .../common\ui.py
- 005 0971:set_option() self.fn_set_option(value)
- 006 0987:mouse_up() self.set_option(self.options[ui])
- 007 0982:mouse_down() def mouse_down(self, mouse): self.mouse_up(mouse)
- 008 1868:modal_main() self.ui_down.mouse_down(self.mouse)
- 009 1846:modal() nstate = self.FSM[self.state]()
- 010 2063:modal() ret = win.modal(context, event)
- .../rfmode\rfcontext.py
- 011 0398:modal() ret = self.window_manager.modal(context, event)
```

**Comment by vxlcoder** [comment] 2018-07-13 18:41
Thanks for the report, @kudamuchi.
The commit 512b5d0 _should_ fix the problem, but I cannot reproduce the original issue.
Can you give me a little more context about what you were doing when this happened?  Are you able to make it happen again?
Thanks!

**Comment by carter2422** [comment] 2018-07-19 19:45
Did you get a chance to test this again @kudamuchi? We're not able to replicate the original issue, but it should be fixed. 

I'm closing this but if it happens again please re-open the issue.

**Closed by carter2422** 2018-07-19 19:45 UTC
Labels: Ready for Testing, bug, can't replicate, tool: polystrips
