### ISSUE TITLE
Symmetry visualization broken

### ISSUE THREAD

**Issue by Nocturael** [CGCookie/retopoflow#567] opened 2018-07-31 09:40 UTC
![screenshot 2018-07-31 11 28 26](https://user-images.githubusercontent.com/2722361/43451791-0c6b2092-94b6-11e8-97b3-816ce783bca8.png)
![screenshot 2018-07-31 11 28 57](https://user-images.githubusercontent.com/2722361/43451792-0ceed0e0-94b6-11e8-9570-3078c2f44e39.png)

**Comment by carter2422** [comment] 2018-07-31 10:10
This is due to the origin of the Target Mesh being off center. 

Like any other object in Blender the RetopoFlow Target Mesh that’s created will be placed at the 3D Cursor upon activation, thus it’s important to double check its location before starting RetopoFlow. 

To fix simply switch to Object Mode, position the 3D Cursor at the center point and then press CTRL SHIFT A > Origin to 3D Cursor.

**Comment by carter2422** [comment] 2018-07-31 10:11
The incorrect scale visualization is a bit odd, but is likely due to a scale issue with other the source or Target object. If you select both and hit CTRL A > Apply Scale the issue should be resolved. 

Handling all object transforms has proven tricky.

**Comment by Nocturael** [comment] 2018-07-31 10:27
The scale is 1 and the origin is the global origin already.

**Comment by vxlcoder** [comment] 2018-07-31 12:03
Will take a look soon.

**Comment by Nocturael** [comment] 2018-07-31 12:06
![screenshot 2018-07-31 14 03 42](https://user-images.githubusercontent.com/2722361/43458489-bda94cf8-94ca-11e8-9b6f-4d6c94191b1a.png)
Starting a new RF object doesn't bug out, but suffers from other visual issues.

**Comment by vxlcoder** [comment] 2018-07-31 12:08
Would you mind sharing your .blend file with us?

The visual issues, unfortunately, are due to how we draw on top of the mesh.  Sharp angles to the view will have these issues, unless you offset the drawing away from the mesh or you always draw on top, both of which have their issues.

**Comment by Nocturael** [comment] 2018-07-31 12:17
I'm afraid I have since done something that fixed the issue. It might have had to do with me starting a new RF object or renaming the bugged one (deletion of some cache?).

**Comment by vxlcoder** [comment] 2018-07-31 12:44
Very strange.  I just cannot figure out how to reproduce this bug.  The target and source meshes are drawn using the same normal offset multiplier, so if one is rendering correctly, they all should render correctly.

If this issue does not show up again soon, I will close this issue.  However, please reopen and post details if you see it again.

Thanks!

**Comment by Nocturael** [comment] 2018-07-31 12:53
Will do, thanks.

**Closed** 2020-12-21 23:35 UTC
