### ISSUE TITLE
Navigation fails when returning to mesh

### ISSUE THREAD

**Issue by GrindingAgony** [CGCookie/retopoflow#661] opened 2018-11-22 22:09 UTC

**Comment by GrindingAgony** [comment] 2018-11-22 22:11
Navigation fails when returning to mesh. Using tubelike stucture, add contours with retopoflow, exit to evaluate, select retopo mesh & return to it to add more contours, & cannot navigate.

**Comment by vxlcoder** [comment] 2018-11-24 11:40
Thanks for the report, @GrindingAgony.

I will need to know a few things to help me diagnose the issue:

- What system you are running on?  (Windows, Linux, Mac.  version)
- What is your language set to?  (we have had navigation issues when language is anything other than English... working on this)
- Which version/branch of RF are you using?
- Can you reproduce it on the default scene (default cube, etc.)?  If you cannot, would you be willing to attach the .blend file that is causing this problem?

**Comment by vxlcoder** [comment] 2018-11-24 14:36
Thanks for the test file, however I cannot reproduce this bug in it.

I'll close this issue for now, but let us know if this happens again.

Thanks!

**Closed by vxlcoder** 2018-11-24 14:36 UTC
