### ISSUE TITLE
PolyStrips tool very buggy when working in orthographic view

### ISSUE THREAD

**Issue by Sarunas86** [CGCookie/retopoflow#689] opened 2019-01-07 20:07 UTC
Hey CGcookie's,
would like to report one issue with retopoflow. When I try to work with polystrips in ortho view it does not work properly. If i try to move any handle it messes up any clean topology (when working in perpective, it is much more stable)

**Comment by Sarunas86** [comment] 2019-01-18 14:46
Hey,
I am using latest blender (2.79b) and latest RF version.
please find attached screenvideo and blend file

**Comment by theoldben** [comment] 2019-02-04 12:30
> Hey CGcookie's,
> would like to report one issue with retopoflow. When I try to work with polystrips in ortho view it does not work properly. If i try to move any handle it messes up any clean topology (when working in perpective, it is much more stable)

Thank you so much for pointing that out. I was using it in orthographic view all the time and wondering why the handles were always flying all over the place. Is that a bug or intended?

**Comment by Juggernaut1994** [comment] 2019-03-29 18:34
> 
> 
> Thanks for the report @Sarunas86.
> 
> Can you please post a screenshot to help us debug this issue? Also, which versions of RF and Blender are you using? If you can post a .blend file, that would be very helpful.
> 
> Thanks!

Here's[ gif ](https://gfycat.com/PerkyFlakyBordercollie)with bug I've discovered today in orthographic view. It seems like it's trying to snap to camera view or to opposite direction somewhere very far away. I'm on 2.79 (not daily build) and 2.0.2 retopoflow.

**Comment by vxlcoder** [comment] 2019-03-29 18:53
ah, that .gif is useful, @Juggernaut1994!  Could you post the .blend file for me to test?  Does this also happen with RF 2.0.3?

Sorry all that I haven't followed through on this issue... I did not see the files posted by @Sarunas86 (seems that they didn't get attached to GH?), and then this issue slipped under my radar.

**Comment by Juggernaut1994** [comment] 2019-03-29 19:56
Same here on 2.0.3. 
Also I've noticed that when curve handles are "flying around" they can be snapped back to mesh by clicking (left click for me) somewhere outside mesh, but it doesn't resolve the mess.
Here's file:
[Ortho-test_.zip](https://github.com/CGCookie/retopoflow/files/3024192/Ortho-test_.zip)

I don't know what kind of info shared in .blend file, but if needed: 
blender hash is f4dc9f9d68b (22.03.18)

**Comment by vxlcoder** [comment] 2019-05-27 16:17
Sorry all for my late reply on this.

Was finally able to reproduce on an ico sphere.

![ps edit in ortho](https://user-images.githubusercontent.com/3790699/58430802-e6e97080-8078-11e9-9edc-e0b806efcf40.gif)

Thanks for the .blend file @Juggernaut1994!  I think this is all related.

Working on this now!

**Comment by vxlcoder** [comment] 2019-05-31 15:56
this bug should now be fixed---finally!

it took so long, because it required lots of debugging and digging.

if you all (@Sarunas86, @theoldben, @Juggernaut1994, @grimakaka) can test out branch `issue/689` to see if it works, that would be helpful.

Thank you all for your patience on this!

![ps edit in ortho works](https://user-images.githubusercontent.com/3790699/58718233-1828b000-839b-11e9-8961-cd2c579d167f.gif)

**Comment by Sarunas86** [comment] 2019-05-31 16:00
Looks nice :) will test when possible

**Comment by carter2422** [comment] 2019-11-21 17:18
@vxlcoder given 2.8 should this still be tested and merged for a point release?

**Comment by KapitanDokgo** [comment] 2020-05-18 06:19
2.79 still not working

**Comment by vxlcoder** [comment] 2021-02-23 00:31
This appears to be working in the latest release.  Closing this issue, but please let us know if you continue to have problems.

Thank you!

**Closed by vxlcoder** 2021-02-23 00:31 UTC
Labels: Ready for Testing, bug, tool: polystrips, v2
