### ISSUE TITLE
[QUESTION] How to get F and shift-F to work?

### ISSUE THREAD

**Issue by quisp-quisp** [CGCookie/retopoflow#1233] opened 2023-06-19 06:07 UTC
Retopoflow Version: v3.30 GitHub

Blender Version/Hash: v3.3.1

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

Although ctrl-F seems to work for the tweak brush, F and shift-F aren't doing anything. I can only change these two values through the menu on the top right corner. Also, pressing F seems to fit my mesh to the viewport window, so I think blender's shortcut keys might be interfering in some way? How can I get these shortcuts to work as intended?

&nbsp;

**How to Reproduce:**

1. Use Tweak brush
2. Try to use F or ctrl-F

**Comment by vxlcoder** [comment] 2023-06-19 10:41
@quisp-quisp, this behavior is by design, where blender keymaps related to view are passed through, because _most_ of the time this is what the artist wants. by default, RetopoFlow's keymaps do not overlap with blender's, so this keymaps collision doesn't usually happen, but they can after customizing either of the keymaps.

there are two options to fix this: you can change blender's keymap or change RetopoFlow's. if you want to keep the F keymap for blender, change the F and Shift+F for RetopoFlow.

you can read the docs for details on changing RetopoFlow's keymaps here: https://docs.retopoflow.com/keymap_editor.html

please let us know if you have any other questions.

**Comment by quisp-quisp** [comment] 2023-06-20 02:52
@vxlcoder ah, thanks so much! that makes sense.

is it possible to have retopoflow temporarily overwrite hotkey collisions when they occur inside the retopoflow mode?
like only when i'm using retopoflow, whenever there's a key conflict it prioritizes the plugin's hotkeys instead of blender's usual hotkeys? and whenever there isn't a key conflict it'll use blender's usual keymappings

**Comment by vxlcoder** [comment] 2023-06-20 11:20
Do you use the `F` shortcut in Blender?

It is possible to have RF override all Blender shortcuts, but it becomes tricky to override only some and it adds complexity for a small use case.

**Comment by vxlcoder** [comment] 2023-06-20 11:48
even switching the code around to have all RF shortcuts override Blender shortcuts will require quite a bit of effort.

**Comment by jlampel** [comment] 2023-07-10 20:42
It doesn't sound like overriding shortcuts would be a good thing to sink time into right now. Closing this out, but if changing the RetopoFlow keymap doesn't work for you, please let us know.

**Closed by jlampel** 2023-07-10 20:42 UTC
