### ISSUE TITLE
Shader crash on AMD in Blender 3.6

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1272] opened 2023-10-28 09:19 UTC
I got this report from the BM inbox, and the customer said that it has happened a few times:

```
- RetopoFlow: 3.4.1
- Build: CG Cookie built for Blender Market
- Blender: 3.06.4 blender-v3.6-release 2023-09-25
- Platform: Windows, 10, 10.0.19045, AMD64, Intel64 Family 6 Model 183 Stepping 1, GenuineIntel

- GPU: {'backend': 'OPENGL', 'device': 'NVIDIA', 'vendor': 'NVIDIA Corporation', 'renderer': 'NVIDIA GeForce RTX 4090/PCIe/SSE2', 'version': '4.5.0 NVIDIA 536.23', 'compute_shader_support_get': True, 'max_batch_indices_get': 1048576, 'max_batch_vertices_get': 1048576, 'max_texture_layers_get': 2048, 'max_texture_size_get': 32768, 'max_textures_frag_get': 32, 'max_textures_geom_get': 32, 'max_textures_get': 192, 'max_textures_vert_get': 32, 'max_uniforms_frag_get': 4096, 'max_uniforms_vert_get': 4096, 'max_varying_floats_get': 124, 'max_vertex_attribs_get': 16, 'shader_image_load_store_support_get': True, 'shader_storage_buffer_objects_support_get': True}

- Timestamp: 2023-10-21 14:51:00.740708

Runtime:

- Undo: select, delete Vertices, select, insert, insert, insert, select, insert, insert, insert
- Error Hash: 9517ae271ce18da931a0624d0820eac1

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'co'

-     C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\retopoflow\rftool_polypen\polypen_insert.py

- 000 0305:set_next_state() self.draw_coords.append([bmv0.co, p0])

-     .../common\fsm.py

- 001 0135:wrapped() return fn(*args, **kwargs)
```

https://blendermarket.com/inbox/conversations/116110

**Comment by vxlcoder** [comment] 2023-10-29 08:28
duplicate of #1261 but it should already been fixed in v3.4.2 in commit 396084f.  will work toward releasing the next version.

**Closed by vxlcoder** 2023-10-29 08:28 UTC
Labels: bug
