### ISSUE TITLE
Polypen crash all the time

### ISSUE THREAD

**Issue by digicraft63** [CGCookie/retopoflow#338] opened 2017-03-25 09:09 UTC
Retopolgy on a sculpted figure in Blender. The tweak function for adjusting the vertices works fine.  Polypen usually causes a crash. 

I don´t understand what the error code is saying but it seems to be the same everytime. Here is the error codes:

EXCEPTION (<class 'IndexError'>): list index out of range
         C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_loopcut\loopcut_data.py
000 0125:find_face_loop() self.face_loop_fs = loop_faces[0]
         C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_loopcut\loopcut_modal.py
001 0183:hover_target() self.loopcut.find_face_loop(self.trg_bme,test_edge)
         C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_loopcut\loopcut_ui_modal.py
002 0060:modal_wait() self.hover_target(context,eventd,settings)
         C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\modaloperator.py
003 0245:modal_main() nmode = self.FSM['wait'](context, eventd)
004 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)

**Comment by vxlcoder** [comment] 2017-04-03 12:19
@digicraft63 thanks for the issue.  could you post a screenshot or the .blend file of the mesh you're retopoing?  i'll look into this today.

**Comment by digicraft63** [comment] 2017-04-03 17:43
Yea, go for it. The file is to large for uploading here so use this link:

**Comment by vxlcoder** [comment] 2017-04-09 17:06
@digicraft63 sorry for the delay.

I've tried opening your .blend a few times, and every time except once Blender 2.78c crashed before loading with a "Bus Error".  The one time it did open, I switched between the different layers to see what you were working on, and one layer had what looked like hair.  Could you make a copy of the .blend file but without the hair?  That would considerably reduce the file size, and it might help with the bus error (I may report it to the Blender devs if I can reproduce it)

Also, looking over the error you pasted, I noticed that it was from LoopCut, not PolyPen.  Are you having troubles with PolyPen, too, or just in LoopCut?  What error is reported within PolyPen?

Two more questions:  Which version of Blender are you using (2.78, 2.78a, 2.78b, 2.78c)?  Which version of RetopoFlow are you using (1.3.0, 1.3.1, etc.)?

Thanks!

**Comment by digicraft63** [comment] 2017-04-10 11:15
OK. I have to get back to vxlcoder later with an updated file. Don´t have the time right now.

Strange that it crashes for you. Maybe it has to do with my computer is more heavy loaded than yours? I have 64 Gb of Ram and four Geforce GTX 1080s, 10 core CPU etc. Blender version is 2.78b. Retopo 1.3.1.

Can you not remove the hair yourself if you happens to be able to open the file again?

As I remember it, it crashes when I use PolyPen but due to the crash report. I might have copied the wrong error report since they look almost identical. It has crashed using LoopCut also but that is more seldom.

I might have a clue for you and that is that it usually works fine when I have a closed retopo grid. It crashes when I try to adjust an object that is not fully covered with retopo polys.

Thank you for looking in to this.

**Comment by carter2422** [comment] 2018-07-25 21:36
Long since resolved via the 2.0 rewrite.

**Closed by carter2422** 2018-07-25 21:36 UTC
Labels: v1
