### ISSUE TITLE
Need BackFace Culling or Hiden Wire active in retopoflow mode

### ISSUE THREAD

**Issue by cloudnix** [CGCookie/retopoflow#270] opened 2016-10-13 06:27 UTC
Hi

Please add BackFace Culling or Hiden Wire active in contours, polyStrips and Polypen Mode.
Need to look clear the topology, please help

thanks

**Comment by carter2422** [comment] 2016-11-23 17:39
Hey @cloudnix, sorry about the late reply. Better backfire culling is a constant focus for us. 

I'm going to go ahead and close this since it's not a bug report, but know that it's a key improvement for us.

**Closed by carter2422** 2016-11-23 17:39 UTC
