### ISSUE TITLE
PolyStrips: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by latheeshvmv** [CGCookie/retopoflow#857] opened 2020-08-03 05:11 UTC
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

The error shows up if I click on the area highlighted

{*add any screenshots of the issue here*}
![image](https://user-images.githubusercontent.com/44595562/89147889-ba32c200-d575-11ea-80b8-a0ecf9846e04.png)

**How to Reproduce:**

Click on while editing. I was actually trying to hide the other components in the screen

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β3
- RF git: b280 6a29283eb48ff19e6d8765d1d0591d7bebd689fa
- Blender: 2.83.3 master 2020-07-22
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce RTX 2060/PCIe/SSE2, 4.5.0 NVIDIA 451.67, 4.50 NVIDIA
- Timestamp: 2020-08-03 10:37:55.852209
- Undo: 

Error Hash: 0a423736e8aad38641977faa6c294915

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'dispatch_event'
-     .../common\ui_document.py
- 000 0448:mousedown_enter() self._under_mousedown.dispatch_event('on_mousedown')
-     .../common\fsm.py
- 001 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment] 2020-08-03 12:00
thanks for the report, @latheeshvmv. will take a look!

**Comment by vxlcoder** [comment] 2020-08-26 14:44
i'm not sure why you ran into this exception, because most events on any area except the main 3D view should be ignored.  I haven't been able to reproduce this error, but I added in a quick check to help prevent this exception from happening again.

Closing for now, but please reopen if you are able to repeat this.

Thank you!

**Closed by vxlcoder** 2020-08-26 14:44 UTC
