### ISSUE TITLE
Unable to select vertices in 2.0.2 in Blender v2.79.

### ISSUE THREAD

**Issue by AGorgal** [CGCookie/retopoflow#685] opened 2018-12-20 21:45 UTC
Hi, I'm pretty sure I'm doing this right, yet I'm unable to select edges nor vertices at all. 
I can "paint" new polys with the pen tool just fine, but I'm unable to select any of the vertices created to edit or delete them. Worse even, if I want to bridge two strokes I can't, because I can't select edges either.

The tool (as far as I know) is on its default settings. 

The relax and tweak tools aren't working either. 

I use the left mouse button to select, so I thought that maybe that was the problem, but I changed that setting, rebooted Blender and the problem continues. 
Any tips?

Here's my Blend file: https://ufile.io/mkhy2

EDIT: I just rolled back to version 2.0 and it works, so I'm guessing 2.0.2 is not meant to be used with Blender 2.79v?

**Comment by vxlcoder** [comment] 2018-12-28 18:53
Thanks for the report and the blend file, @AGorgal!

Right now, RF uses RMB for selection only, regardless of your selection choice in Blender.  We plan to improve this soon.

I've downloaded your blend file, and I see your issue.  I'm looking into it now.

**Comment by vxlcoder** [comment] 2018-12-28 19:12
Ok.  I'm not certain why, but it seems that the Mirror Modifier on the `Cylinder` object is causing the problems.  After applying the modifier, selection (along with everything else) seems to work as expected.  So, for now, maybe use this as a workaround, but I'll look more into fixing this correctly.

**Comment by lexavellino** [comment] 2019-01-17 19:56
I'm having the same issue. I've tried 2.0.2 and 2.0
https://www.dropbox.com/s/95dltfqw3k7o8i6/GLF%20001_Level_Volcano%20Island%2000.blend?dl=0

**Comment by TheChrisHatfield** [comment] 2019-01-23 05:05
I'm having the same issue with Retopoflow. I'm unable to select and move the verities. Making this great addon unusable.

**Comment by TheChrisHatfield** [comment] 2019-01-25 02:35
Any luck finding the issue or any workarounds?

**Comment by vxlcoder** [comment] 2019-01-25 16:17
Ok, I have been able to reproduce it, and I have a not-so-good workaround.  I think the problem is that you're working on a very small model.  And when you're very close to that very small model, element selection breaks.  The workaround is to zoom out.

Working on a better solution now!

**Comment by 3devgit** [comment] 2019-01-25 18:08
hmm... this is a big problem :(

I can create the topology but can then not select any vertex, edge or face(s). Toggle select all does work though.

I have made the base model big/small and applied the scale with the mirror modifier suggestion but nothing seems to work.

Please guys, do your magic to fix this for us :)

**Comment by vxlcoder** [comment] 2019-01-25 19:04
working on it, @3devgit ! :D

**Comment by 3devgit** [comment] 2019-01-25 20:12
Excellent Jon!

I know bugs can be annoying, especially if they aren't easily replicated without a specific mesh and sequence of events in Blender or any application for that matter, lol.

Thanks for jumping on it :)

**Comment by TheChrisHatfield** [comment] 2019-01-26 20:02
Thanks vxlcoder. I released my model was too large and by scaling down fixed the issue.

**Comment by vxlcoder** [comment] 2019-01-26 20:08
Great news! That's helpful. RF is supposed to auto-scale the model to a normal size, so that it shouldn't matter what scale it is. But maybe that's not fully working. Will look further into this.

**Comment by 3devgit** [comment] 2019-01-26 21:58
After more testing I too got it to work by changing the scaling.

A human model 1.77meters in height had to be scaled to 0.09 (0.1 did not work but 0.09 did :/)
A larger model that was 7m tall had to be scaled to 0.001 to work.

I noticed when scaling down too much the dashed drawing lines when using Polypen for example would draw with an offset of where I actually drew the vertex.

It was a case of testing at what scale RF would allow me to select parts of the mesh.

If anyone is interested, to scale your mesh back up to the original scale you will need to do some maths.

The example of the human is a good one:
1. Note the mesh height = **1.77m**
2. Multiply 1.77 by the 0.09 it took to make Retopoflow's selection work correctly = **0.1593** (this is the models new height)
3. Now use RF as you would normally.
4. To scale back up we need to divide the old height (1.77) by the new height (0.1593). Therefore, 1.77/0.1593 = **11.111**
5. Then press Ctrl-A to Apply the Scale in Blender.
6. The model would now be 1.77m tall with a scale of 1.0 in Blender.

Hope that helps :)

**Comment by LagNeto** [comment] 2019-02-26 02:41
The problem is when you are working with centimeters or low units, i was trying to use Retopoflow with some models for UE4 in blender and my units was on Centimeters and a i wasnt able to click any vertice created with Retopoflow. So if someone have a model in centimeters, inches, milimiters u cant be able to click any vertice. 

So if you need a fix just go to your scene properties and change your units preset to something bigger so you dont need to scale your model

**Comment by vxlcoder** [comment] 2019-02-26 19:42
Thanks for the extra details.  Taking a look into this!

**Comment by carter2422** [comment] 2019-11-21 17:19
@vxlcoder do you know if this unit scale issue is still a problem in Blender 2.8?

**Comment by luxalpa** [comment] 2021-02-16 08:45
1m Scale does not work for me in Blender because of selection issue. 100m scale also does not work because of graphical issue. Guess I won't be using this tool. Oh well.

**Comment by vxlcoder** [comment] 2021-02-16 11:42
@luxalpa, would you please share a .blend file that is giving you problems, so that we can try to fix the issue? you can send it to retopoflow@cgcookie.com

**Comment by vxlcoder** [comment] 2021-02-16 12:26
Also, @luxalpa, which version of RetopoFlow are you using? I was able to find a possible selection-causing bug recently, so all known selection issues might be fixed. Perhaps your issue is something different from what we have seen, or we should have you try the latest version of RF.

**Comment by jlampel** [comment] 2023-03-01 18:12
Closing this out since we are not able to focus on maintaining versions for Blender 2.7x. Most folks are at least on 2.8 by now and this has not been an issue since then. If this issue happens in the latest version, please let us know!

**Closed by jlampel** 2023-03-01 18:12 UTC
Labels: bug, v2
