### ISSUE TITLE
Polypen tools allows creation of tris [2.0]

### ISSUE THREAD

**Issue by nearsr** [CGCookie/retopoflow#485] opened 2018-05-21 22:09 UTC
This may already be a known issue, but the polypen happily snaps to existing vertices, making tris. I've made a lot of accidental tris this way, it might be better to make it more difficult or not permit it.

Also, as a temporary workaround for when working with close together geometry, is there a way to disable snap to other vertices in polypen? (And only snap to the sculpt)

**Comment by Tyrannosaurus1234** [comment] 2018-05-22 01:34
The problem you describe, I believe, is due to the fact that the polypen tool relies on constantly being redrawn (probably for the dotted line and face highlight), which leads to **very** poor performance on high detail models such as sculpts, so you click to place a point and then move your mouse, but since it hasn't refreshed yet, the point you just placed is still trailing the mouse and goes wherever your mouse is when the script updates, which in my experience is often as much as 500ms after placing the point. I believe one possible solution to this could be adding an option to disable drawing the dotted line and face highlight, thus removing the requirement for everything to be redrawn constantly, increasing performance, lessening this "lag". I, for one, don't need to physically see what the face I'm about to create will look like considering I already know all of its connecting edges, and in all likelyhood I'm going to hit it with the Relax tool later, so drawing the dotted line and face highlighter leads to serious decreases in performance for no real benefit other than looking neat.

**Comment by vxlcoder** [comment] 2018-06-07 17:43
Thanks for the report, @nearsr!  I've added an option to disable automerge of vertices after moving (see latest commit to `release/2.0`).

**Comment by vxlcoder** [comment] 2018-06-07 17:46
@Tyrannosaurus1234, would you please create a new issue, suggesting the ability to turn off the hints.  Be sure to mention the performance issue, and include your system specs.  If you can post an example .blend file that causes the "lag", please do that too.  That will give us an idea of what the issue is and how to fix it.  Thanks!

**Comment by carter2422** [comment] 2018-07-25 17:42
Since Automerge toggle has been added to Polypen I'm closing this. It works well and prevents the accidental creation of triangles when working in tight spaces.

**Closed by carter2422** 2018-07-25 17:42 UTC
Labels: Ready for Testing, tool: polypen
