### ISSUE TITLE
[BUG] Decreasing/Increasing segments count still does not work

### ISSUE THREAD

**Issue by EtudeinG** [CGCookie/retopoflow#858] opened 2020-08-13 07:16 UTC
Retopoflow Version: 3.0.0 beta2

Blender Version/Hash: 2.83.2

Platform Version/Distribution: Win10

I bought your tool yesterday so I think I'm using the lastest version available.

Changing segments does not work with contours and only increasing with polystrips.

**Comment by vxlcoder** [comment] 2020-08-15 17:47
yes, 3.0.0 beta2 is the latest version.  taking a look at it now!

**Comment by jlampel** [comment] 2020-12-02 16:27
Closing out since this doesn't appear to be reproducible in the latest version.

**Closed by jlampel** 2020-12-02 16:27 UTC
