### ISSUE TITLE
black screen bug blender

### ISSUE THREAD

**Issue by Cesio137** [CGCookie/retopoflow#446] opened 2018-03-31 02:15 UTC
After I finish closing a polygon, type a square, the screen turns black and when I move the mouse in the cime some parts become gray. was in edit mode using the first option of the polygon pen tool

![sem titulo](https://user-images.githubusercontent.com/29849613/38158689-e6fd3ad0-346f-11e8-8ff9-1e8ccb41de03.png)
![toosl](https://user-images.githubusercontent.com/29849613/38158707-2d73fe90-3470-11e8-9753-3fb5a51b59b8.png)

**Comment by vxlcoder** [comment] 2018-04-01 12:17
Thanks for the report, @nathanmiguel123.

Does this happen with the new 2.0 PolyPen?

**Comment by nathanmiguel123** [comment] 2018-04-01 14:57
@vxlcoder Yes, when I finish closing a polygon or a loop this happens

**Comment by carter2422** [comment] 2018-04-01 15:01
@nathanmiguel123 to be certain, your screenshot shows you using version 1.3.x of Polypen, rather than the new v2.0.0 that you just installed. 

Currently v2.0.0 includes both versions of the toolset so that you can try them side-by-side. 

Be sure to start Polypen from the panel that says `RetopoFlow 2.0`

**Comment by nathanmiguel123** [comment] 2018-04-01 16:03
Sorry, but strange because I went in branch release 2.0 and downloaded and installed

**Comment by vxlcoder** [comment] 2018-04-02 15:38
@nathanmiguel123, you do have 2.0 installed, but you're using the PolyPen from 1.3.  Notice in the tool shelf that there are two PolyPen buttons, one under RetopoFlow 1.3 and one under RetopoFlow 2.0.  Try the 2.0 version, and let us know if RF is still crashing.  Thanks!

**Comment by nathanmiguel123** [comment] 2018-04-02 16:09
Not the 2.0 is normal, just the polycount problem too high, causing some brakes at the beginning and when I try to close some geometry with strange angles or with 90 degrees an error message appears

**Comment by vxlcoder** [comment] 2018-04-02 16:18
I'm still confused about your problem.  I'll try to reiterate what I might understand at this point.  Please correct me with what I'm missing or wrong on.  It seems that there are three separate issues here:

PolyPen 1.3 causes the crash and black screen when you create certain geometry.  I can take a look at this soon.

PolyPen 2.0 is working, but also when you try to create geometry, an error message appears?  Can you post a screenshot of the error message?  What type of geometry are you trying to create?

Also, is PolyPen 2.0 running slowly for you?  How is it running slowly?  Just to make sure: note that specifying the target and source meshes in RF 2.0 is different than from RF 1.3.

**Comment by nathanmiguel123** [comment] 2018-04-02 16:40
The second question is that when I try to close a polygon with angles of 90 degrees upwards only the edges appear, but it is not much of a problem since it is only in edit mode and close the faces and the third is that when I use a poligono with 500k of faces for example, it stops for the first 5 seconds then returns to normal and a very high polycount message appears

**Comment by vxlcoder** [comment] 2018-04-02 16:45
> The second question is that when I try to close a polygon with angles of 90 degrees upwards only the edges appear, but it is not much of a problem since it is only in edit mode and close the faces

The face may actually be closed, but you might not see it clearly.  If you can post a screenshot, that would be very helpful in figuring out what the issue is.

> when I use a poligono with 500k of faces for example, it stops for the first 5 seconds then returns to normal and a very high polycount message appears

Unfortunately, we are very limited in what we can do with high poly count source meshes.  To try to make the performance as best as possible, we do a lot of pre-computing.  This could be the delay that you see.  If it is, then it will only happen once each time you open Blender, since it will cache the results.  If you continue to have issues with this, please open a new bug report with details.

Thanks @nathanmiguel123!

**Comment by jlampel** [comment] 2020-12-22 00:05
All issues here seem to have since been resolved. If you continue to have trouble with PolyPen please let us know!

**Closed by jlampel** 2020-12-22 00:05 UTC
