### ISSUE TITLE
Patches: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by jmobley0429** [CGCookie/retopoflow#660] opened 2018-11-20 01:02 UTC
Second time, moving contour loop toward end of  source mesh and the snapping messed up.
-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1070/PCIe/SSE2, 4.6.0 NVIDIA 391.35, 4.60 NVIDIA
- Timestamp: 2018-11-19 19:00:53.829657


Error Hash: ccd86f3e6e5e4b76b4b9f93201fc039c


Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
- .../rfmode\rfmesh_wrapper.py
- 000 0145:co() return self.l2w_point(self.bmelem.co)
- .../rfmode\rftool_patches.py
- 001 0608:<listcomp>() self.vis_bmverts = [(bmv, Point_to_Point2D(bmv.co)) for bmv in self.vis_verts if bmv and bmv not in self.sel_verts]
- 002 0608:prep_move() self.vis_bmverts = [(bmv, Point_to_Point2D(bmv.co)) for bmv in self.vis_verts if bmv and bmv not in self.sel_verts]
- .../common\profiler.py
- 003 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rftool_patches.py
- 004 0561:modal_main() self.prep_move()
- .../rfmode\rftool.py
- 005 0110:modal() nmode = self.FSM[self.mode]()
- 006 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 007 0556:modal_main() self.tool.modal()
- 008 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment] 2018-11-24 12:08
Thanks for the report, @jmobley0429!

I'm not certain how to replicate this issue, so I cannot debug it directly.  If you can reproduce this issue consistently, please add a comment.

In the meantime, I have made some changes in b9f7b42 that might fix this issue.  Let us know if you continue to run into this issue.

**Comment by vxlcoder** [comment] 2018-11-29 02:14
I have tested all I could and was not able to reproduce this issue. I'm closing this issue, but feel free to reopen if it still happens. Thanks!

**Closed by vxlcoder** 2018-11-29 02:14 UTC
Labels: Ready for Testing, bug, can't replicate
