### ISSUE TITLE
Contours: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by jmobley0429** [CGCookie/retopoflow#659] opened 2018-11-20 00:54 UTC
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1070/PCIe/SSE2, 4.6.0 NVIDIA 391.35, 4.60 NVIDIA
- Timestamp: 2018-11-19 18:53:35.332695


Error Hash: 77a2953f80d29ca508d7647fe7f8173a


Trace:

- EXCEPTION (<class 'ValueError'>): Vector.angle(other): zero length vectors have no valid angle
- .../rfmode\rftool_contours_utils.py
- 000 0323:align_to() q = Quaternion(n0.cross(n1), n0.angle(n1))
- .../rfmode\rftool_contours.py
- 001 0388:modal_move() cl_cut.align_to(cloop)
- .../common\profiler.py
- 002 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- 004 0110:modal() nmode = self.FSM[self.mode]()
- 005 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 006 0556:modal_main() self.tool.modal()
- 007 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment] 2018-11-24 13:11
Thanks for the report, @jmobley0429.

I'm not sure how to reproduce the issue you reported, but fb5e376 might fix it.

Please let us know if you continue to have problems.

**Comment by vxlcoder** [comment] 2018-11-29 02:05
I have tested all I could and was not able to reproduce this issue. I'm closing this issue, but feel free to reopen if it still happens. Thanks!

**Closed by vxlcoder** 2018-11-29 02:05 UTC
Labels: Ready for Testing, bug, can't replicate, tool: contours

**Comment by jmobley0429** [comment] 2018-11-29 04:11
Thank you for your responses! Keep up the good work.
