### ISSUE TITLE
The mash of Retopoflow is sinking in the target object

### ISSUE THREAD

**Issue by Elisha-Dvir** [CGCookie/retopoflow#1007] opened 2021-06-12 16:35 UTC
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment] 2021-06-12 16:38
thanks, @Elisha-Dvir, for the report.

I am not sure what you mean by "sinking in the target object". are you able to provide some more details, especially screenshots or steps for reproducing the issue?

**Comment by Elisha-Dvir** [comment] 2021-06-13 05:46
Hello Jon

Thank you for reaching out. I intended to include those screenshots in my post but the template in github was too complicated for me (I am a simple user, not a developer).

My view is looking like the file 'Poor visibility mesh.jpg' (attached).

 

The only way I can display it properly is turning on the X-Ray on the target object. Then it displayed like screenshot ' X-Ray view.jpg' (attached). But it is so inconvenient to work on this manner that I am considering to stop learning your beautiful addon.

 

I tried many changes in my displaying options but could not get it right. Maybe there is something I am missing.

 

If you need my blender file I'll be happy to send it to you (it exceed the size limit).

 

Thanks

 

 

_____

Elisha Dvir

972-52-3738817

https://www.artstation.com/elisha-dvir

**Comment by vxlcoder** [comment] 2021-06-13 12:55
hmm. it seems your attached image didn't attach to the GitHub issue.

let's try this instead: send an email to retopoflow@cgcookie.com.  there you should be able to attach images and maybe even the blend file, or use Dropbox or other file sharing tool and email a link.

**Comment by vxlcoder** [comment] 2021-06-13 13:02
wait, is this your screenshot? it weirdly showed up in our slack channel but not in GitHub.  if this is you screenshot, are you using a different shader? are you using cycles or Eevee? RetopoFlow only renders correctly in solid or workbench.  might still be best to see what you're seeing but sending a blend file if possible. thanks!

![Screenshot_20210613-085711.png](https://user-images.githubusercontent.com/3790699/121808207-6842da00-cc25-11eb-8694-2d75a4ed6002.png)

**Comment by Elisha-Dvir** [comment] 2021-06-13 17:57
Although my file size is only 5518 KB gmail issue an error ' because it exceeds the size limit.'
I have uploaded it to my google drive.

https://drive.google.com/drive/folders/13-CgKZi8JCrTopZ7uv83YUQLTH_RZcIk?usp=sharing

 

Thanks

_____

Elisha Dvir

972-52-3738817

https://www.artstation.com/elisha-dvir

**Comment by vxlcoder** [comment] 2021-06-14 13:24
Ok, @Elisha-Dvir, I think I see what you're referring to.

There are two items at play here that make it difficult to see and work with the target mesh:

- the target mesh is low res, so details of the source mesh are popping through the faces of the target
- the current view settings are not quite right for the task

![image](https://user-images.githubusercontent.com/3790699/121897480-6bef6300-ccf0-11eb-985d-0d762daa292a.png)

With the first item, increasing the resolution of target mesh (ex: add extra edge loops) will better capture the details of source mesh.  this is non-ideal, since you're trying to reduce the poly count.  Note: the vertices of the target mesh will _always_ be on the surface of the source mesh (this is by design for RetopoFlow), but the edges / faces won't follow the source mesh.

with the second item, there are a few things you can try.  unfortunately, there is no solution that will solve every visualization problem perfectly.  this is a problem that exists for all graphics, unfortunately.  it is impossible to get right for all possible working cases (orthographic view along with normal offset, view clipping, etc.).  so you might have to adjust your settings based on where you're currently working.  i've listed three below that produce workable results.

1. working in perspective view tends to work better with the view settings.
    ![image](https://user-images.githubusercontent.com/3790699/121897861-c7215580-ccf0-11eb-8177-7e9a1909fca0.png)
2. adjust the view clipping end value (was `341.2`, changed to `10000`)
    ![image](https://user-images.githubusercontent.com/3790699/121899276-42373b80-ccf2-11eb-9396-ddc3e811dae3.png)
3. adjust the alpha below (was `0.02`, changed to `0.8`)
    ![image](https://user-images.githubusercontent.com/3790699/121899224-33e91f80-ccf2-11eb-8333-f0b1e66951e1.png)


please let me know if any of these solved you problem or if I completely missed what you were originally reporting on.

**Comment by Elisha-Dvir** [comment] 2021-06-14 14:25
Thank you so much.

Each of your tips did the trick. Especially the first one (display it on the perspective view).

I'll go on learn this addon. And furthermore, to recommend it to the Israeli blender facebook group.

 

However, there is a small issue on the UI of this program: 

When blender user enters a selected field in a dialog box, he can type a new value which automatically replaces the existing one. On your addon you first have to delete the existing value and then to type a new one.

 

Thanks again.

 

_____

Elisha Dvir

972-52-3738817

https://www.artstation.com/elisha-dvir

**Comment by vxlcoder** [comment] 2021-06-14 15:05
Glad to hear that the suggestions worked for you!

Yes, we do know that the input boxes act differently from how Blender's input boxes act.  This is on our to-do list.

i'm going to close this issue, but please let us know if you have any other problems.

happy retopo'ing, and thanks for the recommendation!  if you have time, we would appreciate a positive rating on the RetopoFlow page on the Blender Market ([link](https://blendermarket.com/products/retopoflow))!

**Closed by vxlcoder** 2021-06-14 15:05 UTC

**Comment by Elisha-Dvir** [comment] 2021-06-14 16:41
I followed your link to blender market but I could not figure out where I can add my rating.

Thanks.

 

_____

Elisha Dvir

972-52-3738817

https://www.artstation.com/elisha-dvir

**Comment by vxlcoder** [comment] 2021-06-14 18:41
Try the URL below, @Elisha-Dvir.

https://blendermarket.com/products/retopoflow/ratings#new_product_rating

**Comment by Elisha-Dvir** [comment] 2021-06-17 07:23
Hello

I have another issue: After joining to meshes (had and body), I can't see Retopoflow menu on the edit mode.

I have uploaded my file here <https://drive.google.com/drive/folders/13-CgKZi8JCrTopZ7uv83YUQLTH_RZcIk> .

 

Thanks

 

_____

Elisha Dvir

972-52-3738817

https://www.artstation.com/elisha-dvir

**Comment by Elisha-Dvir** [comment] 2021-06-17 14:18
After working on this file (with F2 addon) your menu reappeared. I wander what happened.

 

Thanks.

 

_____

Elisha Dvir

972-52-3738817

https://www.artstation.com/elisha-dvir

 

From: ***@***.*** ***@***.***> 
Sent: Thursday, June 17, 2021 10:23
To: 'CGCookie/retopoflow' ***@***.***>
Subject: RE: [CGCookie/retopoflow] The mash of Retopoflow is sinking in the target object (#1007)

 

Hello

I have another issue: After joining to meshes (had and body), I can't see Retopoflow menu on the edit mode.

I have uploaded my file here <https://drive.google.com/drive/folders/13-CgKZi8JCrTopZ7uv83YUQLTH_RZcIk> .

 

Thanks

 

_____

Elisha Dvir

972-52-3738817

https://www.artstation.com/elisha-dvir

**Comment by vxlcoder** [comment] 2021-06-17 14:26
I'm not entirely sure.  I'll take a look at your linked blend file soon.

If this happens again, would you mind opening a new issue so that we can better track it?  Also, if at all possible, can you post what you see in the terminal here.  There might be a bug that's getting reported there but not by RF.  To do this on windows, simply click on Blender's Window menu item, then Toggle System Console (or something like that).  If you're running linux/mac, you'll have to run Blender from a terminal prompt.  Let me know if you have questions on how to do that.

Thanks for the updates!

**Comment by vxlcoder** [comment] 2021-06-17 16:18
ah, i _might_ know what the problem is...

When you're in Edit Mode and there are no other visible meshes (other than the one you're currently editing), then the RF menu will not show.  you'll need to make another mesh (ex: `High res decimated`) visible for the RF menu to show.

**Comment by Elisha-Dvir** [comment] 2021-06-18 16:13
Thanks. I'll check it.

 

_____

Elisha Dvir

972-52-3738817

https://www.artstation.com/elisha-dvir

**Comment by vxlcoder** [comment] 2021-06-18 16:22
note: we changed the condition for when the RF menu will appear.  now, it should appear any time you're in Object mode or Edit mode (on a mesh).  warning messages will show and the RF buttons will be disabled if no source meshes are found.
