### ISSUE TITLE
PolyPen: Assert Error!

### ISSUE THREAD

**Issue by Nit-Pick** [CGCookie/retopoflow#501] opened 2018-06-29 20:54 UTC
Trying to retopologize a model made of tris that was originally made in cinema 4d, it's a robot with thin walled parts that causes the verts of retopoflow to clip inside the other side of the wall or spaz out. Flying everywhere only on the thin walled parts. This comes up a lot when that happens.
-------------------------------------
```
RetopoFlow: 2.0.0 beta
Blender: 2.79.0

- EXCEPTION (<class 'AssertionError'>): unhandled type of other: None (<class 'NoneType'>)
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\common\maths.py
- 000 0105:__sub__() assert False, "unhandled type of other: %s (%s)" % (str(other), str(t))
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rfmesh.py
- 001 0719:nearest2D_bmedge_Point2D() diff = bmv1 - bmv0
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rfcontext_target.py
- 002 0116:accel_nearest2D_edge() return self.rftarget.nearest2D_bmedge_Point2D(xy, self.Point_to_Point2D, edges=edges, max_dist=max_dist)
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rftool_polypen.py
- 003 0088:set_next_state() self.nearest_edge,_ = self.rfcontext.accel_nearest2D_edge(max_dist=10)
- 004 0117:modal_main() self.set_next_state()
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rftool.py
- 005 0103:modal() nmode = self.FSM[self.mode]()
- 006 0107:modal() raise e
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rfcontext.py
- 007 0472:modal_main() self.tool.modal()
- 008 0396:modal() nmode = self.FSM[self.mode]()
```
(edited for readability)

**Comment by vxlcoder** [comment] 2018-07-04 01:06
Thanks for the report, @Nit-Pick.  I've added a line of code that should prevent this error from coming up, but I'm still not sure how it happens.  Could you post a screenshot or the .blend file so that I can search for a root cause?  Thanks!

**Comment by vxlcoder** [comment] 2018-07-25 18:35
I'm closing this issue for now.  If you see this problem again, please reopen and post a .blend file.
Thanks!

**Closed by vxlcoder** 2018-07-25 18:35 UTC
Labels: bug, can't replicate, need more info
