### ISSUE TITLE
Can't find in Blender 2.80

### ISSUE THREAD

**Issue by Damolx** [CGCookie/retopoflow#726] opened 2019-06-28 11:48 UTC
Hello everyone,

Yes i know this question seems a little bit dumb but how can i run this tool on Blender 2.80, i know that the actual version isn't stable but it should work on it, no ? 

I can't find the tool in blender....

Thanks.

**Comment by oddmore** [comment] 2019-06-29 20:41
I can't seem to find it either in blender 2.8. It asks to update to blender 2.8x (which it already is that version).

**Comment by vxlcoder** [comment] 2019-06-29 22:10
Hi all.

Right now, RF only works in 2.79, but we are working on a 2.80 version now. Will update once we have a beta (or maybe alpha) version ready to test.

**Comment by TeoLions** [comment] 2019-06-30 18:36
> 
> 
> Hi all.
> 
> Right now, RF only works in 2.79, but we are working on a 2.80 version now. Will update once we have a beta (or maybe alpha) version ready to test.

Any ETA on it? 2.8 seems to be getting a release in July, it would be so awesome to have Retopoflow by then!

**Comment by Damolx** [comment] 2019-07-01 14:35
Ok thanks for the responses, i'll wait.

**Comment by genics** [comment] 2019-07-02 10:59
can you tell us what is the time you plane to release the beta ver. I will so excited to test it.

**Comment by heavydetail** [comment] 2019-07-29 17:42
What type of help do you need to get this ready for 2.80?

I made it load in 2.8 by changing the requirements, and yes, it fails with numerous errors like:
`Caught exception while attempting to search for classes
  cls: RFTool: RFTool_Stretch, RFTool_Stretch, RFTool_Patches, RFTool_Strokes, RFTool_Loops, RFTool_PolyPen, RFTool_Relax, RFTool_Tweak, RFTool_Contours, RFTool_PolyStrips
  pyfile: tools.watch_profile
  No module named 'Levenshtein'`

a runtime error:
`Error: Registering panel class: 'RF_PT_Panel' has category 'Retopology'`

and a bunch of `assign as a type annotation` warnings.

**Comment by vxlcoder** [comment] 2019-07-30 18:54
as @heavydetail has noted, making RF work for 2.80 requires some significant changes due to the reworking of blender python api (especially opengl), and these changes have taken longer than I had anticipated.  we are actively working on it, even though GitHub might not show, because the work is under the b280 branch along with the b280 branch of CookieCutter.  i'm hoping to have a working vertical slice of RF by the end of the week.

**Comment by genics** [comment] 2019-07-31 02:39
I don't know what is vertical slice. but it sounds good news.

**Comment by tdw46** [comment] 2019-07-31 21:56
Oh sweet! I'm so excited for this plugin to be ready for 2.8! It's the last piece of the puzzle for me to migrate over!

**Comment by genics** [comment] 2019-08-05 01:31
any news? brother?

**Comment by watpalders** [comment] 2019-08-05 02:30
Stoked, CANT WAIT

**Comment by carter2422** [comment] 2019-08-19 14:48
@genics we are making very good progress! You can see some teasers posted on @vxlcoder's twitter: https://twitter.com/gfxcoder

P.S. I'm closing this issue as it's not a bug; the 2.8 version will be released just soon as we can and it will be emailed to all existing customers.

**Closed by carter2422** 2019-08-19 14:48 UTC
