### ISSUE TITLE
Contours: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by bmv2011** [CGCookie/retopoflow#856] opened 2020-07-15 07:34 UTC
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β2
- Blender: 2.83.2 master 2020-07-09
- Platform: Windows, 10, 10.0.17763, AMD64, Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1070 Ti/PCIe/SSE2, 4.5.0 NVIDIA 432.00, 4.50 NVIDIA
- Timestamp: 2020-07-15 08:33:47.380077
- Undo: cut, tweak move, tweak move, tweak move, tweak move, tweak move, insert, insert, insert, insert

Error Hash: 2a1de537f6e24d10f04e9a321bd0667e

Trace:

- EXCEPTION (<class 'ValueError'>): edges.new(): this edge exists
-     C:\Users\Barry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh.py
- 000 1493:new_edge() bme = self.bme.edges.new(verts)
-     C:\Users\Barry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rf\rf_target.py
- 001 0459:new_edge() return self.rftarget.new_edge(verts)
-     C:\Users\Barry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rftool_contours\contours_ops.py
- 002 0299:new_cut() edges += [self.rfcontext.new_edge((v0, v1))]
-     C:\Users\Barry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 003 0141:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\Barry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rftool_contours\contours.py
- 004 0614:new_line() self.new_cut(ray, plane, walk_to_plane=False, check_hit=xy01)
-     C:\Users\Barry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 005 0104:_callback_tool() fn(self.rftool, *args, **kwargs)
- 006 0123:callback_actions() self._callback_tool('action', *args, **kwargs)
-     C:\Users\Barry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_linecut.py
- 007 0075:modal_line() self.callback_actions()
-     .../common\fsm.py
- 008 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment] 2020-08-26 14:14
Thanks for the report, @bmv2011!

Sorry that it's taken us so long to reply to this problem!

This is a very confusing issue, because the code is creating new edges between brand new vertices.  Overall, I haven't been able to figure out how to reproduce, and I'm just guessing at this possible solution in latest commit ^^

Do you happen to recall what you did to cause this to happen?  For example, were you working on a symmetric target (mirror turned on) and you created a new cut that crosses the mirror plane?  Was this caused by accidentally clicking on the mesh?

The only thing I can possibly think of that might cause this is if you had somehow tried creating a Contour loop with only 2 vertices in it... but there are checks in place to try to prevent this.  I've added one more check to try to prevent this from happening again.

Will close this issue for now.  If you have more info, and especially if it happens again, please reopen the issue.

Thanks!

**Closed** 2020-08-26 14:14 UTC
Labels: can't replicate, need more info, tool: contours
