### ISSUE TITLE
3d Model legs pushed together 

### ISSUE THREAD

**Issue by Creedling** [CGCookie/retopoflow#1236] opened 2023-06-26 01:06 UTC
So when I open retopflow my model does this. Any insights would be appreciated 

![Screenshot 2023-06-25 200515](https://github.com/CGCookie/retopoflow/assets/137737340/ff2dd2e3-d1a9-4f6d-8981-9d57ce8fdcaa)

**Comment by vxlcoder** [comment] 2023-06-26 01:08
@Creedling that's an issue we haven't seen before!

any chance you can send your .blend file to retopoflow@cgcookie.com?

**Comment by vxlcoder** [comment] 2023-06-26 15:32
Thanks for sending the .blend file, @Creedling!

the issue is caused by the source meshes having an armature.  presently, RF scales the source objects, target object, and scene so that the sources fit into a known size.  by eliminating the scale of everything, we can tune RF's visualizations to work well for most setups.  but this approach is _not_ a "silver bullet".  at the moment, the armature isn't scaled along with the sources, so when the sources get resized, the relative scales are out-of-whack, so things go weird.  interestingly, the arms and torso do not have issues... only the legs.

two workarounds at the moment are:

- disable the armature showing in the viewport, or
- apply the armature to a duplicate of the source and hide the original.

i know that neither are ideal options.  i tried a couple of quick fixes to get this situation to work, but they each caused more problems.  for now, i've added a warning to the RF Blender menu.  will take another stab at this issue after this next release.

**Comment by Creedling** [comment] 2023-06-26 15:42
Thank you for your response

**Comment by jlampel** [comment] 2023-07-10 20:38
A warning in the RF menu seems good enough. I think working to support all edge cases in RF 3 is not something we need to do if we can spend that time working on RF 4, which should make these kinds of issues irrelevant in the first place.

**Closed by jlampel** 2023-07-10 20:38 UTC
Labels: hack
