### ISSUE TITLE
User Interface and Viewport lag Issue

### ISSUE THREAD

**Issue by ILMGI** [CGCookie/retopoflow#1025] opened 2021-07-09 02:31 UTC
Hi, there seems to be an issue with the user interface and lag in viewport with RF v3.2.0 (from GH) on Blender 2.9.
The operating system I am running blender on is Windows 10 and I am also using intel integrated graphics.
issue:
1) There seems to be weird artifacts on the user interface just like #753 
![issue 1](https://user-images.githubusercontent.com/87159673/125014349-fe341e00-e086-11eb-92d2-5b2fda1e0b58.png)
2) The viewport performance drops significantly as symmetry is turned on and the symmetry line also has artifacts
![issue 2](https://user-images.githubusercontent.com/87159673/125014354-ff654b00-e086-11eb-91a7-8858d0fb2bad.png)

**Comment by vxlcoder** [comment] 2021-07-12 17:28
Thanks for the report, @ILMGI!

this is indeed the same issue as #753 and #879, but thus far we haven't been able to reproduce it on any of our machines to run tests.

question to start debugging this issue: are you running this on mac hardware (whether bootcamp/dual boot or virtual machine)?  so far, we have only seen this issue show on mac hardware.  but if you're on a regular pc, we now have new info to work with!

The symmetry line visual artifacts are a combination of a few things:

- yes, there was a bug in how symmetry is rendered in version 3.2.0.  this has been fixed in 3.2.1 (not yet released).  you can test by updating to the `v3.2.1` branch (see [link](https://docs.retopoflow.com/addon_updater.html) for details)
- the default cube has a very low poly count, which is generally not the type of model RF expects to retopologize.  in other words, the symmetry line renders more correctly if the poly count of source is much higher (using subd modifier, subdividing the mesh, using a different and higher-res mesh, etc.)

**Comment by vxlcoder** [comment] 2021-07-14 20:43
for those with this issue, can you please try the `v3.2.1` branch to see whether the committed changes improve this visual bug?  see [link](https://docs.retopoflow.com/addon_updater.html) for details.

also, if possible, can someone post a video capture of using RetopoFlow with this visual issue?  I have a few other hypotheses that I think a video might provide the right evidence.

in particular, can you capture the following in the video:

- start with default cube
- start RF
- move the main/poly count/options windows around the screen slowly
- try minimizing / restoring each of the windows
- create new geometry using one of the tools
- rotate the view around just a bit
- open the help menu
- slowly scroll through the help
- try resizing the entire blender window very slowly

i think doing the items above might expose what the issue _might_ be.  thank you!!

**Comment by vxlcoder** [comment] 2021-09-10 19:08
Hi @ILMGI!

I think I might have found the cause of this issue (and other similar issues), and now we have a solution!

Please, if you're still having this issue with RetopoFlow v3.2.2, follow the steps on using the [RetopoFlow Updater System](https://docs.retopoflow.com/addon_updater.html) to try out commit c1d4f0f.

IMPORTANT: be sure to start with v3.2.2 before updating to the commit!  the previous updater system had a bug that was fixed in v3.2.2.

Please let me know here if you

- continue having this issue even after checking out commit c1d4f0f, or
- no longer experience this issue after checkout out commit c1d4f0f, or
- were experiencing this issue before but it stopped being an issue even before checking out commit c1d4f0f.

If no comments are posted to this issue by the beginning of Oct 2021, I plan to close this issue.

Thanks!

**Comment by ILMGI** [comment] 2021-09-11 19:43
Hello @vxlcoder 

Sorry for the late reply I was busy with some work and didn't noticed your response. I have read all your suggestions and here is what I found.

First, I removed Retopoflow v3.2.0 and updated to v3.2.2 and then tried commit c1d404f using Retopoflow updater system. 

Upon first three attempts trying to update to commit c1d404f, Blender staright up crashed. However, with some patience I did manage to update it. After installation Retopoflow tab indicated that I was still on v3.2.2. 

Then I tried creating a new Retopoflow target and Blender immediately stops responding.
![retopoflow_crash](https://user-images.githubusercontent.com/87159673/132959560-1d304fc1-27e9-407e-b352-6333334a0265.png)

Then I restarted Blender and the Retopoflow tab was missing from the options tray. 
![retopoflow_crash2](https://user-images.githubusercontent.com/87159673/132959580-6790111a-dcc5-4ba6-bbb1-76237e7ae626.png)

Upon opening the preferences tab I noticed that Retopoflow v3.2.3 was installed. However, there seems to be no way of using it because of the missing tab.
![retopoflow_crash3](https://user-images.githubusercontent.com/87159673/132959590-cc63c3c9-575e-4c14-8942-6335ec647bc9.png)

Personally, I think that this issue occurs on device running on intel integrated GPUs, so it might be a driver related bug.

I hope my response was of help

**Comment by vxlcoder** [comment] 2021-09-11 19:46
thanks for the details, @ILMGI.

I am away from keyboard, but will take a look as soon as possible.

thanks for your persistence, and sorry for the troubles. will get you up and running!

**Comment by vxlcoder** [comment] 2021-09-11 19:49
actually, @ILMGI, try this:

- uninstall and remove any versions of RF
- restart blender
- download and install in blender the zip file linked below
- then try enabling

https://www.dropbox.com/s/r5o8opzmz2jb06p/RetopoFlow_v3.2.3-alpha.zip?dl=0

again, thanks for your help in debugging this!

**Comment by ILMGI** [comment] 2021-09-11 19:51
Hi @vxlcoder,

I will try your fix in a few hours. Should I also reinstall Blender as well?

**Comment by vxlcoder** [comment] 2021-09-11 19:55
no. just uninstall any copies of RetopoFlow

**Comment by ILMGI** [comment] 2021-09-12 16:17
Hi @vxlcoder 

I tried RF v3.2.3 and to no surprise the visual artifacts originally shown remained. However, the viewport performance did increase according to my experience.

I still think this issue is graphic driver related and will probably arise in any computer running integrated intel graphics.

Hope this helps.

**Comment by vxlcoder** [comment] 2021-09-12 16:20
sad to hear that it wasn't fully fixed.

weirdly, I have tested on machines with Intel integrated graphics, but they worked fine.  might be certain combo of things that cause it.

will continue testing and researching, though!

**Comment by jfranmatheu** [comment] 2024-12-16 13:10
Closing issue due to prolonged inactivity. From what I've seen, It's unclear if the issue is fixed in later versions (nor reported back by issuer) or if it's a gpu driver issue (lack of info). But if the issue persists, please feel free to reopen it. Thank you!

**Closed by jfranmatheu** 2024-12-16 13:10 UTC
Labels: help wanted, can't replicate, need more info
