### ISSUE TITLE
[BUG] Some of the shortcuts don't work

### ISSUE THREAD

**Issue by BlinkerHigh** [CGCookie/retopoflow#1285] opened 2023-11-26 03:13 UTC
Retopoflow Version: 3.4.2

Blender Version/Hash: 3.6

Platform Version/Distribution: Windows

- Double click to select edgeloop doesn't work.
- Pressing - or + to increase/decrease cuts in any tool doesn't work

How to Reproduce:
- It didn't work from the start so I have no replication steps to share.

**Comment by vxlcoder** [comment] 2023-11-26 04:00
thanks for the report, @BlinkerHigh.

this is a very unusual issue, as we haven't had an issue like this before. I know you said that it never worked, but would you mind providing a bit more information to help debug it?  for example...

can you replicate this on the default scene with default cube? which other keymaps work as expected? does inserting new geometry work?  can you select a single edge using contours? does select in polypen work?

also, can you post screen grabs of what you see, either as a still or as video? this goes a.bit beyond just stating what all the steps you tried to get these two ops to work.

thanks for helping us debug it!

**Comment by jlampel** [comment] 2024-01-29 21:44
In the select tool, double click to select a loop is not part of the keymap and same with the + and - keys to shrink or grow selection. Closing this out since it's not a bug, but I agree that they are helpful and should be supported. Luckily, this should not be an issue in the upcoming version 4, and we need to focus on that rather than add all Blender features into version 3.

**Closed by jlampel** 2024-01-29 21:44 UTC
