### ISSUE TITLE
[BUG]Viewport rotate with RMB issue

### ISSUE THREAD

**Issue by Dprasni** [CGCookie/retopoflow#1067] opened 2021-12-30 12:17 UTC
---

Retopoflow Version: 3.2.5

Blender Version/Hash: 3.0

Platform Version/Distribution: Win 10 / MS Store

&nbsp;

**Issue:**

Cant rotate my viewport when i have the RMB set to Rotate View with "Click Drag", the context menu will also not show up in this combination even when i set it up as "Click"

I tried with my custom keymaps, and i have made a new Blender default copy of the keymaps and only changed these two things, everything else is factory.
MMB works for rotation.

{*add any screenshots of the issue here*}
![Snimka zaslona 2021-12-30 131318](https://user-images.githubusercontent.com/46623153/147751072-359a50d4-ac91-4c78-9af2-baffcac0e408.jpg)
![Snimka zaslona 2021-12-30 131342](https://user-images.githubusercontent.com/46623153/147751077-f170b334-fa1b-4811-a5e9-9e2966c54dfe.jpg)

&nbsp;

**How to Reproduce:**

- Set viewport navigation to rotate view with RMB - click drag, context menu object to - Click

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment] 2022-01-02 16:24
Thanks for the report, @Dprasni.

This is a key action that we haven't fully tested (there are too many to test thoroughly), but I'll take a closer look.

**Comment by vxlcoder** [comment] 2022-01-06 22:37
Ok. I see what the problem is, but I'm not sure how to correct it, because your keymap is an unusual set up.

RetopoFlow handles the various actions (keys, mouse, timer, etc.) internally to simplify responding to different user actions.  But when certain navigation actions are performed inside RF, RF will explicitly pass those events off to Blender so Blender can handle them.  Usually the MMB Press is used for rotating the view.  So when you use this normal setting, RF passes the MMB Press event on to Blender as soon as the MMB is pressed, and all works as expected.  If you were to use RMB press for rotating 3d view, RF would pass that on to Blender, and all would work as expected.  However, in your special case, you want RightMouse Drag to be used for rotating.  So, when you first press down the RMB, RF sees this event and waits (it's a RMB Press, not a Drag yet).  But once you start dragging, then RF sees the RMB Drag, and tries to pass this on to Blender, but Blender has already forgotten about the RMB Press already, and therefore ignores the RMB Drag.  (blender looks for Click/Press followed by Drag, but only sees the drag)

One possible option is to call the corresponding view navigation Blender op directly once we detect a navigation event (in this case, RMB+Drag -> 3d view rotate).  However, I'm not convinced this would even work, as Blender might still think that RMB+Press did not happen (because RF saw that event and waited for Drag), so Blender might just immediately end the op.  Testing this option to see if it works could also require a significant amount of effort.

Another option is to do our own view rotation rather than passing the event on to Blender and allow Blender to do this work.  However, this would be produce duplicate code from Blender into RF, and I'd like to avoid this as much as possible.

Another option is to add a "blender passthrough" action to the keymap editor, where any actions defined there would simply get passed through to Blender.  Here, we could add RMB+Press to be passed through, so once RMB is pressed, Blender would see that immediately, and then possibly it would see the Drag and handle the rotation as expected.  Not only is this a highly specialized hack (this is the only case where such a hack would be needed as far as I can tell), it would also prevent other actions involving RMB from being usable (ex: cancel on RMB+Click).

(note: this would not be a problem if there was a way to push events back to Blender, but to my knowledge there isn't a way to do this)

I'll think on this for a while.  maybe there is another option that I'm not noticing at the moment.

In the mean time, I've implemented the blender passthrough option as a workaround (to be pushed to GH soon).  Note: if you have Shift+MiddleMouse or Shift+RightMouse, you'll need to add them to the passthrough also.  This is not a great solution, but it works around your particular keymap set up.

**Comment by vxlcoder** [comment] 2022-01-06 22:52
see commit 12dc3a0.

you can use the updater system ([doc](https://docs.retopoflow.com/addon_updater.html)) to try this out.

**Comment by vxlcoder** [comment] 2022-01-11 13:34
sorry to hear that. I will get a zip file for you to install soon.

**Comment by vxlcoder** [comment] 2022-01-11 17:29
@Dprasni, below is a link to download the current alpha version of v3.2.6.  My suggestion is to remove RF from Blender, then download and install RF from the link below, then restart Blender, and try starting RF.

[link](https://www.dropbox.com/s/9oowdbxlqokr27h/RetopoFlow_v3.2.6-alpha.zip?dl=0)

Let me know if you continue to have issues or if this does fix your issue.  Thanks for helping us work through this!

**Comment by Dprasni** [comment] 2022-01-11 20:51
No problem,

Ok, managed to install it and run properly now,

The passthrough works but is a bit janky in my case, i've mapped it to the key next to the LShift key (i think only the EU keyboards have that key><), .

When pressing (and holding) the first time the passkey it works for the first action but becomes a bit unpredictable when calling the menu and then click dragging to rotate the mouse. However releasing and pressing the passkey everytime i want to rotate or call the menu everything works predictably.

So conclusion is when holding down the pass key, things get a bit wonky and unreliable.

**Comment by jlampel** [comment] 2023-02-27 22:33
I'm closing this out because the original issue was worked around, and there have been some keymap improvements since then that should benefit this case as well. If you have any issues with the most recent version, please feel free to open a new issue.

**Closed by jlampel** 2023-02-27 22:33 UTC
Labels: Ready for Testing, action map
