### ISSUE TITLE
Loops: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by emilsvfx** [CGCookie/retopoflow#492] opened 2018-06-10 04:50 UTC
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.Also, change the title of this bug report to something descriptive and helpful.
Thank you!
-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.4

- EXCEPTION (<class 'UnboundLocalError'>): local variable 'sel_only' referenced before assignment
-          C:\Users\Homepc\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\retopoflow-master\rfmode\rftool_loops.py
- 000 0110:modal_main() if sel_only: self.rfcontext.deselect_all()
-          C:\Users\Homepc\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\retopoflow-master\rfmode\rftool.py
- 001 0103:modal() nmode = self.FSM[self.mode]()
- 002 0107:modal() raise e
-          C:\Users\Homepc\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\retopoflow-master\rfmode\rfcontext.py
- 003 0472:modal_main() self.tool.modal()
- 004 0396:modal() nmode = self.FSM[self.mode]()

**Comment by vxlcoder** [comment] 2018-07-03 22:49
Thanks for the report!  This is a duplicate of issue #461, which has already been fixed.  You can get the fix by pulling the latest commit of branch `release/2.0.0` or waiting just a few more days for the RF 2.0 Beta 2 release.  Closing for now.

**Closed by vxlcoder** 2018-07-03 22:49 UTC
