### ISSUE TITLE
Tweak Relax is destroying mesh

### ISSUE THREAD

**Issue by CenekStrichel** [CGCookie/retopoflow#268] opened 2016-10-05 10:30 UTC
Sometimes it is working, but very often I am getting this when I use Tweak + Relax (LMB + Shift)
Blender 2.77, RF 1.2.2, 1.2.1

![tweakrelax](https://cloud.githubusercontent.com/assets/8094238/19109837/6ea7d2c0-8af7-11e6-8f1f-664bdddf1724.gif)

**Comment by vxlcoder** [comment] 2016-11-23 17:38
@CenekStrichel Thank you for the video screenshot.  Can you give details on the model?  Specifically, what is it's "size"?  Is the object scaled?

**Comment by CenekStrichel** [comment] 2016-11-24 09:56
Here is model. I think that problem is not in size, but specific shape.

[bug.zip](https://github.com/CGCookie/retopoflow/files/610950/bug.zip)

**Comment by vxlcoder** [comment] 2016-11-26 01:56
ok, @CenekStrichel, i see what the problem is...  both objects are scaled by 0.001, and right now tweak doesn't work well when the objects are transformed (translated, rotated, scaled).  we are planning to revamp the tools to work better under transformations, etc, but for now a workaround is to apply the transformations (ctrl+a, location; ctrl+a, rotation & scale).

**Comment by CenekStrichel** [comment] 2016-11-27 08:11
ouch! I overlooked this. Works great now, thank you.

**Comment by carter2422** [comment] 2016-11-27 21:52
I assume the scale is somewhat related to #242  @vxlcoder ?

**Comment by vxlcoder** [comment] 2016-11-27 21:55
i think relax is ignoring the transformation matrix.  i tried fixing it quickly yesterday, but i could not get it working right.  will revisit soon

**Comment by carter2422** [comment] 2016-12-12 19:26
Closing, what with work-around found. This is somewhat related to #242 and should be further improved later.

**Closed by carter2422** 2016-12-12 19:26 UTC
Labels: bug
