### ISSUE TITLE
Exception Attribute Error

### ISSUE THREAD

**Issue by Weisl** [CGCookie/retopoflow#292] opened 2016-12-14 17:07 UTC
Hi, 

When I am entering the polystrip mode an exception appears. It enters the polystrip mode and I can draw the lines as usual but nothing appears. After applying the polystrip after mode with enter the lines I have drawn appear. 

![2016-12-14 18_05_06-blender_ e__000_work_bm_bm_svn_bm_creation_trunk_visuals_locations_castle_inter](https://cloud.githubusercontent.com/assets/6353016/21192206/0d5dbe18-c228-11e6-8cec-0d4ce44384eb.png)
Entering the polystrip mode

![2016-12-14 17_21_33-blender e__000_work_bm_bm_svn_bm_creation_trunk_visuals_locations_castle_interi - kopie](https://cloud.githubusercontent.com/assets/6353016/21192217/167168ce-c228-11e6-80f0-2af4b2d9d9a1.png)
drawing the lines as usual

![2016-12-14 17_21_50-blender e__000_work_bm_bm_svn_bm_creation_trunk_visuals_locations_castle_interi](https://cloud.githubusercontent.com/assets/6353016/21192221/1c0eaa30-c228-11e6-8f5d-48e7f39edd30.png)
nothing appears 

![2016-12-14 18_05_16-blender_ e__000_work_bm_bm_svn_bm_creation_trunk_visuals_locations_castle_inter](https://cloud.githubusercontent.com/assets/6353016/21192185/02c545ac-c228-11e6-8315-3ca3a040dc01.png)
after applying the strikes appear 

[RetopoFlow_log.txt](https://github.com/CGCookie/retopoflow/files/652334/RetopoFlow_log.txt)

**Comment by carter2422** [comment] 2016-12-14 17:09
@Weisl any chance you could share the model you're working on? I'd like to run some tests here.

**Comment by Weisl** [comment] 2016-12-14 17:19
I can not but it online, I can send it to you in confidence per mail.

**Comment by carter2422** [comment] 2016-12-14 17:20
Sure thing. You can email it jonathan@cgcookie.com

**Comment by carter2422** [comment] 2016-12-14 17:34
Thanks @Weisl; I'm investigating.

**Comment by Weisl** [comment] 2016-12-14 17:34
I have sent you the entire model with wetransfer. When I export this part of the model as its own blend file, polystrips work normally.

**Comment by carter2422** [comment] 2016-12-14 17:40
@Weisl I've confirmed the issue in the file you sent, and also confirmed that it works as expected if you append the object into a new file. _This is a workaround for now, but obviously not ideal._

I'm attempting to narrow down the cause in the file.

**Comment by carter2422** [comment] 2016-12-14 17:50
@Weisl I've narrowed it down to an issue with there being many objects in the scene. To test this, simply delete all other objects in the scene and then Polystrips will work. 

I'm trying to replicate the problem on a default scene so that I can fix it. 

Thanks for the report.

**Comment by Weisl** [comment] 2016-12-14 18:04
@carter2422  Thank you for your commitment. It's really appreciated

**Comment by carter2422** [comment] 2016-12-14 18:43
@Weisl good news. I found and fixed the problem. Can you please uninstall your current version of RetopoFlow and then install this one? 
[RetopoFlow-v1.2.5.zip](https://github.com/CGCookie/retopoflow/files/652555/RetopoFlow-v1.2.5.zip)

You should find Polystrips to work as expected on the full scene now.

**Comment by Weisl** [comment] 2016-12-14 19:44
@carter2422 Polystips works. But using polypen throws errors now and makes the display appearing black. 

![polypenerror](https://cloud.githubusercontent.com/assets/6353016/21198026/f73f08f6-c23d-11e6-9ccd-7bfd5987b813.png)



![2016-12-14 20_36_42-einstellungen](https://cloud.githubusercontent.com/assets/6353016/21197951/9d37c7a8-c23d-11e6-8a02-2f909fcce657.png)
after entering polypen mode 


[polypen_log.txt](https://github.com/CGCookie/retopoflow/files/652696/polypen_log.txt)

**Comment by carter2422** [comment] 2016-12-14 19:45
@Weisl investigating

**Comment by carter2422** [comment] 2016-12-14 20:00
@Weisl the problem was due to my change in #294. I've reverted the commit and will find a better solution.

For now you can use:
[RetopoFlow-v1.2.5b.zip](https://github.com/CGCookie/retopoflow/files/652747/RetopoFlow-v1.2.5b.zip)

**Comment by Weisl** [comment] 2016-12-14 20:23
Polypen crashed twice since I installed the version from above. I got the strange black screen thing in blender.
 
![polypenblack](https://cloud.githubusercontent.com/assets/6353016/21199243/f997c804-c242-11e6-9d5d-a0f82606cf88.png)

[Polypen_02_log.txt.txt](https://github.com/CGCookie/retopoflow/files/652780/Polypen_02_log.txt.txt)

**Comment by carter2422** [comment] 2016-12-14 20:36
@Weisl what steps are you taking to get that crash? I'm not able to replicate that at all. 

Did you restart after removing and installing the v1.2.5b version? From the error log you included it appears to be the original issue, which means you're running stale code and Blender needs to restart.

**Comment by Weisl** [comment] 2016-12-15 14:02
I started blender several times new and I also tried to reinstall the addon. Doesn't work. With the character model I have the same problem. 
[polypen.zip](https://github.com/CGCookie/retopoflow/files/654820/polypen.zip)

**Comment by carter2422** [comment] 2016-12-20 20:17
I'm closing this since the original issue has been resolved in 1.2.5. @Weisl if you run into additional Polypen issues go ahead and open a new issue for each.

Thanks!

**Closed by carter2422** 2016-12-20 20:17 UTC
Labels: bug
