### ISSUE TITLE
Constant app crushes with use of polypen in Blender 2.78

### ISSUE THREAD

**Issue by shamsfk** [CGCookie/retopoflow#345] opened 2017-07-12 08:52 UTC
I tried retopoflow for a day and it currently can't be worked with using polypen :( 

The error on the screenshot (and some other which has a longer description but is less frequent I will screenshot it when it pops again) is popping out every minute or so (I saw it hundreds of times in a day) and if I don't Ctrl+Z right after it but continue drawing - it crashes blender UI to a black flickering screen (thank god it is possible to save while UI is crashed :)

https://www.dropbox.com/s/mz9sony6afpz8ar/Screen%20Shot%202017-07-12%20at%2011.41.03.png?dl=0

Sometimes it not just pops an error out but also creates not a normal quad but with 2 internal crossed edges and whole thing above is applicable in that case too.

P.S. And I'm on 5k iMac and selecting edges is a PAIN - like 50-70% of the whole working time is spent on trying to aim at them (vertices are a bit better but painful too).

**Comment by shamsfk** [comment] 2017-07-12 09:10
Just a comment made in a very sad state of frustration:

It IS the worst software experience I had in recent years. 

I saw several negative comments on a blender market and decided to try it out first. And it was such a wise decision. I can only pity those who spent a buck on it.

For a first brief moment, I thought - hooray! it is great! begone topogun! But very soon it became a disaster (

**Comment by shamsfk** [comment] 2017-07-12 13:16
https://www.dropbox.com/s/29jejkvwtpr0rjl/Screen%20Shot%202017-07-12%20at%2016.14.10.png?dl=0

I'm making a new object - making a vertex, a second one, the third one does this, every time, no matter where I place the first 2.

**Comment by vxlcoder** [comment] 2017-07-12 13:16
I'm sorry to hear that polypen is crashing so frequently for you, @shamsfk!  We do our best to test the tools prior to release, but finding all problems can be difficult since every machine and Blender set up is different.  And unfortunately, most of the negative comments for RF have been due to someone running into a problem like this but not reporting it.  Thank you for taking the time to give us the info we need to debug and fix this problem!

Since these kinds of crashes happen very rarely for us, would you please share with us a .blend file that is causing these issues regularly on your machine so we can test it here?  It does not need to be a particularly interesting file, but one that has this issue pop up.

Edge selection should be a relatively easy fix.  When you're trying to select an edge, is it simply not selecting them, or selecting the incorrect thing?

**Comment by shamsfk** [comment] 2017-07-12 13:20
Edges are very very thin, they are unclickable, I need to find the exact position of a mouse to actually select it, and sometimes this selection window is several pixels long, and like 1 pixel tall, so on 5k display, it is very hard to click.

**Comment by shamsfk** [comment] 2017-07-12 13:21
I will try to distil a blend file, as the whole thing is like over a gig.

**Comment by vxlcoder** [comment] 2017-07-12 13:22
thanks, @shamsfk!

**Comment by shamsfk** [comment] 2017-07-12 13:26
https://www.dropbox.com/s/ndyup8t9ly2wqi5/adventurer-bugfile.blend?dl=0

here it is. there is a sculpt and a polypen object.
Algorithm is:
select polypen obj,
go to polypen tab,
select sculpt as base mesh,
insert 2 verts with polypen,
insert third one.

It crashes on a third one.

**Comment by vxlcoder** [comment] 2017-07-12 13:27
@shamsfk, when you're using polypen, does it correctly highlight the edge your mouse is hovering over?

**Comment by vxlcoder** [comment] 2017-07-12 13:33
@shamsfk, we are able to replicate your crashes here.  Can you try turning off the view lock to see if that prevents the crashes?  I'm wondering if the view lock might be the cause.

**Comment by vxlcoder** [comment] 2017-07-12 13:43
Also, we noticed that the object is scaled really small.  Can you try applying the scaling transformation to the source object (Object > Apply > Scale)?  Another option is to scale the object larger, and then apply the transformation.  These are only workarounds, but they might help in preventing the crashes.

We have seen in the past that a transformation on the object can cause problems.  Unfortunately, it's not an easy fix in the current version RetopoFlow (1.3.1).  However, the next version (2.0) is rebuilt from scratch to handle better these situations.

**Comment by shamsfk** [comment] 2017-07-12 13:53
1) it does highlight it properly when I'm able to aim at it
2) what is the view lock? If it is on, it must be by mistake, because I don't know what is it
3) I will try it now

**Comment by shamsfk** [comment] 2017-07-12 14:03
Applying a scale did the trick. It stopped crashing.
AND - selecting edges became much easier! holy moly, it's like a miracle)
You probably should write in all caps in the readme for people to apply transforms until you fix it.
It is like 2 different pieces of a software :)

**Comment by vxlcoder** [comment] 2017-07-12 14:08
Ha!  I'm glad to read that the problems went away!  (again, it's only a workaround, but it does seem to work)

Please let us know if you have any other problems.  For now, I'm going to close the issue, since RF 2.0 _should_ not run into this problem.

Thank you again for reporting the issue!  We can only fix the problems that we know about :)

**Closed** 2017-07-12 14:10 UTC
